### ISSUE TITLE
Html Widget to pull tools by query

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#10]
# jmcejuela says ...

Use case: group wants to show case all its tools in its own webpage, with all the info kept in the elixir registry

This should be simple enough for any group to pull the JSON and create an interface list of it. However, this could be made easier and more standard for all users as a general widget. Furthermore, the widget could include something like "Powered by Elixir Registry" to make some kind of publicity of the registry itself.

Matus commented that one group already has this specific to their needs. Cannot promise anything at this moment, but would like to standardize this and use the widget on the rostlab.org webpage.
# matuskalas says ...

Thank you @jmcejuela . Various institution would benefit from having something like this.

It is, however, a request for the Tools Registry, not EDAM. But let's leave it here until the Tools Registry has it's own GitHub repo ;-)
# jmcejuela says ...

True, I realized that later when I posted :-)

Thanks!

**Comment by jmcejuela** [comment]
Yeah, it's now open source :dancer: :)

**Comment by joncison** [comment]
It's been ... errrr ... some time :) but we now have this:
https://github.com/bio-tools/biotoolsSum

which is a well featured client-side web application for rendering views and reports of tool descriptions.  The CZ guys behind it would be keen to collaborate more *e.g.* customisations, applications *etc.*

So I close this.
