### ISSUE TITLE
We need persistent unique IDs also for individual operations and input and output parameters

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsregistry#102]
This is a copy of a common issue between https://github.com/bio-tools/biotoolsxsd and https://github.com/bio-tools/biotoolsregistry. Please discuss common things in https://github.com/bio-tools/biotoolsxsd/issues/28

**Comment by joncison** [comment]
We're a (very) long way from needing or being able to support this in bio.tools.
