### ISSUE TITLE
Unique persistent IDs versus names (e.g. IDs have to be valid XSD NCNames)

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsregistry#103]
I remember we discussed this and related things many times. To remind and to record it among GitHub issues, a couple of crucial notes to repeat. Let's please continue discussing this here. (And eventually split concrete _todo_ tasks from here.)
1. IDs have to be valid XSD **NCNames**, in addition to be valid **and convenient** in **cool URLs**, in order to be usable in RDF/XML!
2. IDs have to unique, especially for software and databases, _i.e._ _e.g._ http://bio.tools/softwareToolName. Thus first-come-first-serve, **just like when creating one's email address**.
3. **Available** (uniqueness) and **valid** (cool URL and NCName) IDs should be auto-generated for tools from their **short name**, at registration time for new records, and in semi-automated semi-manually-curated refactoring push for the already registered (together with merging records**!**).
4. We need at least 2 or (rather) more names (short, long, ...), as also has been noted repeatably elsewhere.

**Comment by matuskalas** [comment]
Add **unique** and **cool**: the IDs and the corresponding _httpd_ and APIs do also have be **CASE INSENSITIVE!**

That is, any case typed, will resolve properly.

**Comment by joncison** [comment]
@matuskalas - I'm fairly sure all of this (except one thing, see below) is now implemented, so closing this.  cc @ekry FHI.

"We need at least 2 or (rather) more names (short, long, ...), as also has been noted repeatably elsewhere."
- will you please request this on:
https://github.com/bio-tools/biotoolsSchema/issues/new
