### ISSUE TITLE
Enable sorting by Citation rate (total or recent)

### ISSUE THREAD

**Issue by TKlingstrom** [bio-tools/biotoolsRegistry#106]
I was just on a Skype meeting with Jon Ison and he told me to suggest this here.

To identify the most popular tools it would be very useful to count the citations or Altmetric rating of the publications affiliated with a tool. Preferably this could be done with the user being allowed to select both the accumulated number of citations and an adjusted metric to identify tools rapidly rising in popularity.

**Comment by KarelBerka** [comment]
At least it could be good to visualize number of citations in a similar fashion as PDBe (http://www.ebi.ac.uk/pdbe/entry/pdb/1tqn) does - from CiteXplore: http://www.ebi.ac.uk/Tools/webservices/services/archive/literature/citexplore_clients

**Comment by joncison** [comment]
We have a milestone due in 2017 Q4 so work for "literature integration" is in the roadmap (http://biotools.readthedocs.io/en/latest/changelog_roadmap.html#q4) - something like this should definitely be included.

**Comment by joncison** [comment]
@TKlingstrom @KarelBerka you can now sort by citation count in bio.tools

Charts of citations for a publication of a tool are available via biotoolsSum:
https://github.com/bio-tools/biotoolsSum
https://biotools-sum.firebaseapp.com

(either in the tools view, or report mode)

It would be very nice to include such charts directly in bio.tools (see https://github.com/bio-tools/biotoolsRegistry/issues/210)
