### ISSUE TITLE
Adding of formats: CSV, idXML, KNIME tables

### ISSUE THREAD

**Issue by julianu** [bio-tools/biotoolsregistry#108]
Hej, I don't know whether this is the correct place to ask for this, but we need some more file formats, which we can use for input and output at bio.tools:
* CSV: the simple comma separated values
* idXML: an XML format, used mainly by OpenMS to store all intermediate information (that is proteomics data like spectrum identification, protein identification, quantification of both). Maybe @timosachsenberg or @jpfeuffer can help to specify this more.
* KNIME datatable: for tools, which run inside KNIME (www.knime.org), it might be interesting whether those directly create KNIME tables or plain files

**Comment by joncison** [comment]
Wrong tracker!

Please post the question here instead:
https://github.com/edamontology/edamontology/issues

Thanks !

**Comment by julianu** [comment]
Thanks for pointing me there!
