### ISSUE TITLE
Similarity search 

### ISSUE THREAD

**Issue by KarelBerka** [bio-tools/biotoolsregistry#110]
It would be good to add similarity search within the tool page using EDAM. 

In that way, user would be able to find similar tool to one, which she used but for any reason she cannot use any longer.

**Comment by joncison** [comment]
This is in the roadmap, mooted for 2017 Q4
http://biotools.readthedocs.io/en/latest/changelog_roadmap.html

cc @ekry FHI

**Comment by joncison** [comment]
This is duplicating https://github.com/bio-tools/biotoolsregistry/issues/39

Preserving comments in this thread in above.
