### ISSUE TITLE
control and update EDAM ontology terms upon push to biotools

### ISSUE THREAD

**Issue by hmenager** [bio-tools/biotoolsregistry#112]
Hello,
While testing ReGaTE with the new bio-tools, I noticed that there is currently:
- no check on the term labels which are pushed in a json description to bio-tools
- no server side handling to fill the label
My understanding so far was that the only part of EDAM concepts in pushed data would be the "URI", not the "TERM", and that the term would be updated server-side to push there the corresponding EDAM label. Current actual situation is:
- if I push {"uri":"http://edamontology.org/format_1929", "term":"pippi langstrumpf"}, it will be accepted as is and pippi langstrumpf will be the label appearing in dev.bio.tools
- if I push {"uri":"http://edamontology.org/format_1929"}, the "term" will remain empty in dev.bio.tools.
Help @ekry ! Cc @joncison, @fmareuil and @odoppelt...
Hervé

**Comment by ekry** [comment]
Hey Hervé,

W disabled most (if not all) EDAM checking/validation on dev.bio.tools, since we’re doing some testing due to merging and migrating data from bio.tools and dev. This will of course be enabled once we go into production.

Best wishes,
Emil

**Comment by hmenager** [comment]
Good. I should probably close this issue, then, right?
Hervé

**Comment by ekry** [comment]
Yes, please =)

Emil

**Comment by hmenager** [comment]
this is a temporary matter, as stated by @ekry
