### ISSUE TITLE
Subdomains, additional search capabilities

### ISSUE THREAD

**Issue by veitveit** [bio-tools/biotoolsRegistry#116]
Can we add general search and search within EDAM terms when adding tools in the subdomain interface? This will help to group e.g. topic-specific tools.

Nice feature by the way!

**Comment by joncison** [comment]
@veitveit : quite a bit of search was added.  Could you please check and see if more is needed?  Otherwise I'll close this issue.

**Comment by joncison** [comment]
@veitveit : I think the search function for subdomain creation is adequate, but reopen if you disagree!
