### ISSUE TITLE
Help text (hover-over . labels to pop-up tool tips from biotoolsSchema)

### ISSUE THREAD

**Issue by hedip** [bio-tools/biotoolsRegistry#117]
When filling in annotations help text would be helpful. Could be get when hovering to a ? next to the input box. 
Specific example where it is needed is the format of DOI

**Comment by joncison** [comment]
Tool tips as currently defined in biotoolsSchema 2.0.0 (https://github.com/bio-tools/biotoolsSchema/tree/master/versions/biotools-2.0.0) will be the start - we can extend those too tips later as necessary.  Agree getting syntax hints would be very nice.

**Comment by joncison** [comment]
Related to https://github.com/bio-tools/biotoolsregistry/issues/8

**Comment by joncison** [comment]
See https://github.com/bio-tools/biotoolsregistry/issues/121

**Comment by joncison** [comment]
hi @hedip - this done and staged for release

**Comment by joncison** [comment]
cc @hedip
