### ISSUE TITLE
Subdomain edit interface can't find new tools

### ISSUE THREAD

**Issue by profgiuseppe** [bio-tools/biotoolsregistry#118]
After registering new tools to bio.tools, I tried to add them to our subdomain (bologna.dev.bio.tools)
However, the search interface is not finding them by name, neither they show up in the result for a "credits" query (that however shows the previously added tools).

**Comment by baileqi** [comment]
Can you please check if you add tools to the same server (dev.bio.tools not bio.tools) as the domain? I tried to reproduce and can't seem to replicate the issue.

**Comment by profgiuseppe** [comment]
The tools were added to bio.tools and not to dev.bio.tools. I expected that both sites would be looking at the same data.

**Comment by joncison** [comment]
bio.tools and dev.bio.tools use a different back-end; could you pls. try again and report back here if you still have a problem?  Thanks!
