### ISSUE TITLE
Click on Topic and Operation labels to perform corresponding search via API

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#120]
In Tool Cards and Query Interface

It would be nice to have two options (via pop-up menu from clicking on term)
1. Perform search via bio.tools API
2. Navigate to EDAM

**Comment by khillion** [comment]
I think the default behavior should be to perform a search with the corresponding term. We could have a more detailed description by hover over, opening a window with several information, and a link somewhere.

For instance:

## FASTQ
* **Definition**: FASTQ short read format ignoring quality scores.
* **ID**: http://edamontology.org/format_1930

More information: [OLS](https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fformat_1930) - [BioPortal](https://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fformat_1930&jump_to_nav=true)

**Comment by joncison** [comment]
Anne says ..."I agree that there should be a more direct link to related tools (stronger ties with the ontology), such as clicking an operation to find tools performing the same operation."

**Comment by joncison** [comment]
The current implementation (in bio.tools) is partially broken, but this now fixed and staged for release

cc @khillion

**Comment by joncison** [comment]
cc @khillion
