### ISSUE TITLE
Migrate existing license annotations to biotoolSchema 2.0.0-compatible enum

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#125]
For mapping see:
https://docs.google.com/document/d/1tqw7FELV4F_qzrTA9KpVYoORAeFPyY1ZOjaGTPN2H1E/edit#heading=h.lnxq458vti9n

This can be done automatically by flagging up any license values that don't match the enum, then applying the mapping - in case something doesn't match post it here.

**Comment by hansioan** [comment]
Does the long form to short form license mapping at the link below contain all the possible values for the old (long form) licenses? I know for a fact that the short form licenses currently in bio.tools are way more than those listed in the document

**Comment by redmitry** [comment]
No.

that was (the real) example. I am not sure about the equivalence.

the list:

AGPL-3.0 // gives me an error although look correct
BSD 3-Clause License (Revised) => "BSD-3-Clause" // ???
Creative Commons Attribution 3.0 Unported
Creative Commons Attribution NonCommercial
Creative Commons Attribution NonCommerical NoDerivs
Creative Commons Attribution 4.0 International
ODC Open Database License
Creative Commons Attribution NonCommercial ShareAlike => 
"CC-BY-NC-SA-??" // unknown version
Creative Commons Attribution Share Alike
CBS License
GNU General Public License v2 => "GPL-2.0"
BSD 3-Clause License (Revised)
MIT License => "MIT"
Apache License 2.0 => "Apache-2.0"
GNU Affero General Public License v3
GNU General Public License v3 => "GPL-3.0"
Creative Commons Attribution 3.0 Unported
GNU Lesser General Public License v2.1 => "LGPL-2.1"
CeCILL v2 => "CECILL-2.0"

**Comment by joncison** [comment]
Thanks Dmitry

@hansioan : will you please apply the mapping above (refactor the content).  Also please confirm the schema enum is now enforced for new entries (it should be!)

``AGPL-3.0`` is certainly defied in biotoolsSchema - this needs checking (adding?) on the bio.tools side

@redmitry : I'd suggest to discard (or better still find the correct version) for "CC-BY-NC-SA-??"

**Comment by hansioan** [comment]
@joncison @redmitry Is there a complete mapping list or does it need making? @redmitry The list you added below in the comment seems to abruptly end at "CeCILL v2". Is that the entire list? I am a bit confused.

**Comment by joncison** [comment]
I *think* changes for the mapping in the OP was done, but @redmitry is suggesting new offending cases which need acting on.  But I'm not sure. @ekry may be able to advise (or just take a look)

**Comment by hansioan** [comment]
OK so the point is that we don't know all the mappings, we do know some and we have to figure out some.

**Comment by hansioan** [comment]
@joncison @redmitry I took all the distinct licenses from the DB and these are:

CBS License
NULL
Creative Commons Attribution NoDerivs
GNU General Public License v2
CeCILL v2
GNU Affero General Public License v3
Apache License 2.0
MIT License
BSD 3-Clause License (Revised)
GNU Lesser General Public License v2.1
Creative Commons Attribution Share Alike
GNU General Public License v3
Creative Commons Attribution 3.0 Unported
Creative Commons Attribution NonCommercial ShareAlike
Creative Commons Attribution NonCommercial

Creative Commons Attribution 4.0 International
GNU Free Documentation License v1.3
Creative Commons Attribution NonCommerical NoDerivs
ODC Open Database License
Non-Profit Open Software License 3.0
GPL-3.0
CECILL-2.1
BSD-3-Clause
GPL-2.0
Artistic-2.0
CC-BY-NC-4.0
CC-BY-NC-SA-4.0
MIT
LGPL-2.1
EUPL-1.1
CECILL-2.0
MPL-2.0
LGPL-3.0
AGPL-3.0
Apache-2.0
CDDL-1.0
Proprietary
Other
BSD-4-Clause
CPL-1.0
Artistic-1.0
CC-BY-NC-ND-4.0
EPL-1.0
GFDL-1.3
ISC
CECILL-B
CC-BY-ND-3.0
CC-BY-4.0
CC-BY-NC-1.0
CC0-1.0

**Comment by joncison** [comment]
Cool - so these need checking against biotoolsScema enum: any which do not match will need to be mapped, then refactored in the DB.

This is one-off job: registration via UI and API should only allow valid license annotations (please check / confirm that).

**Comment by redmitry** [comment]
The list is complete - it has all licenses I was unable to import.
There are 588 unrecognized records, but most of them are repeated.
