### ISSUE TITLE
Systematic de-duplication of credits is needed (from Anne Wenzel)

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#129]
See e.g. 
https://bio.tools/tool/NetMHCpan/version/2.8

Many other examples

**Comment by joncison** [comment]
another type of example (to inform the checks for this):
https://bio.tools/tool/LocARNA/version/1.8.7

**Comment by hansioan** [comment]
Duplicated: see #167

**Comment by hansioan** [comment]
I think at this point all obvious credit duplicates (if not all entirely) are removed. Won't close this until the duplication detection is automated.
