### ISSUE TITLE
Refactor credit of "rnateam"  (from Anne Wenzel)

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#136]
see e.g. https://dev.bio.tools/tool/LocARNA/version/1.8.9

Anne says ...

"It mentions:

rnateam | Institute | Provider
Now, I’m not sure how they entered it in the first place, but (after looking at 'Creditable entities’ and 'Creditable roles’ at https://docs.google.com/document/d/1tqw7FELV4F_qzrTA9KpVYoORAeFPyY1ZOjaGTPN2H1E/edit#heading=h.c7o1s9gkagiz ) eventually this should be:

RNA tools and software consortium | Consortium | Documentor"

**Comment by hansioan** [comment]
I changed the credit instance: rnateam | Institute | Provider
to 
RNA tools and software consortium | Consortium | Documentor
