### ISSUE TITLE
Only render horizontal scroll bar in grid view if it's needed (from Anne Wenzel)

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#139]
May not be "simple" :)

**Comment by joncison** [comment]
this is related to https://github.com/bio-tools/biotoolsregistry/issues/130

**Comment by joncison** [comment]
To clarify, if I select options to show in "Grid view" such that horizontal scroll is needed, I must first scroll down to the bottom of the page to find the horizontal scroll bar : the usability is horrible

**Comment by joncison** [comment]
@bug1303 : I think this now fixed.  Please confirm & I'll close.

**Comment by bug1303** [comment]
I can confirm that the horizontal scroll bar now is only rendered if actually needed, however your comment from June 6 still stands:  

> must first scroll down to the bottom of the page to find the horizontal scroll bar : the usability is horrible!

**Comment by joncison** [comment]
Pls. log that as a new issue ("render horizontal scroll at top of grid view" or some such).  Thanks!
