### ISSUE TITLE
publication is mandatory in web interface

### ISSUE THREAD

**Issue by osallou** [bio-tools/biotoolsRegistry#14]
When creating a new tool, publication is mandatory. However it is not the case through the API.
All tools do not have a publication, this field should not be mandatory

**Comment by joncison** [comment]
@osallou a quick note on this (very old) issue - I think now >90% of entries have publications, but very soon (once we migrate to [biotoolsSchema ](https://github.com/bio-tools/biotoolsschema)3.0.0) it will no longer be a requirement for registration.  See comment about the tool info. standard in https://github.com/bio-tools/biotoolsregistry/issues/274.
