### ISSUE TITLE
Make a Homepage for the registry

### ISSUE THREAD

**Issue by khillion** [bio-tools/biotoolsRegistry#142]
The actual homepage of bio.tools is a bit raw and a nice homepage could makes the registry more "user friendly". Using the EDAM-based description, we could easily imagine a way to navigate through the registry by topics, operations and so on. A lot of features could be added there and should be discussed.

**Comment by joncison** [comment]
this related to https://github.com/bio-tools/biotoolsregistry/issues/40

although there could be other ideas to have a more attractive splash page ...

**Comment by joncison** [comment]
@khillion - we will get to this, it will be a basic homepage (ideally linked to a vamped menus and footer, see https://github.com/bio-tools/biotoolsRegistry/issues/358)

from discussing this with @hansioan this is a bit harder to do than it appears

**Comment by JenHarrow** [comment]
@joncison I would move this to critical for release as need a home page with a summary of tools content similar to https://orbit.nlm.nih.gov/browse-repository (should be simple to do) and give the user an idea what bio.tool contains

**Comment by joncison** [comment]
this is covered in the new design, but will bump to critical and do a quick fix in the meantime cc @hansioan

**Comment by joncison** [comment]
from https://github.com/bio-tools/biotoolsRegistry/issues/366

1. Help the first time user on bio.tools. What is this site? (Quick Win)
What does this site do? How can it help me?  When I land on bio.tools I’m not really sure what it is. It’s straight into the search/results interface, and the documentation link is hard to spot. How do we think users will discovery bio.tools? Perhaps they need some context on what it is for.

**Comment by joncison** [comment]
done, hope you like it @JenHarrow !
