### ISSUE TITLE
2.1 Add "Contact" in web site header

### ISSUE THREAD

**Issue by heinzstockinger** [bio-tools/biotoolsRegistry#146]
Currently, it doesn’t (easily) seem to be possible to provide feedback or input. I suggest we add an explicit "Contact" in the page header + a way to submit comments/issues etc. For example, a page explaining that issues/comments should be reported via GitHub + URL to the "issues" page.

That is very much required by users of the portal that want to suggest changes.

**Comment by joncison** [comment]
I agree this would be very easy to do and be a big win ... just a "Get help" button (mail to registry-support) or "Log issue" button (linking to GitHub)

cc @ekry @baileqi - nice one to do sooner rather than later?

**Comment by joncison** [comment]
To implement this, see the broader issue of menu improvements (https://github.com/bio-tools/biotoolsregistry/issues/236)

**Comment by baileqi** [comment]
Added as a footer in the bottom of the page.

**Comment by joncison** [comment]
some improvements to https://dev.bio.tools, but we're not quite there yet ... see https://github.com/bio-tools/biotoolsRegistry/issues/236
