### ISSUE TITLE
Subdomain does not show tools

### ISSUE THREAD

**Issue by profgiuseppe** [bio-tools/biotoolsregistry#148]
The subdomain does not show the added tools.
- subdomain: bologna.bio.tools
- 9 tools have been added, the green confirmation banner appeared
- all the tools added are shown into the "Resources included in subdomain" in the "Edit" page

**Comment by joncison** [comment]
I wonder if it takes a little while for the change to propagate. Hmm.  cc @ekry

**Comment by ekry** [comment]
Dear Giuseppe,

This is fixed now.

Best wishes,
Emil

**Comment by joncison** [comment]
@profgiuseppe please check and close the issue once you're happy

**Comment by profgiuseppe** [comment]
Tested the solution by adding few more tools to the subdomain, the view updated immediatly. Thanks.
