### ISSUE TITLE
Subdomain search shows duplicated tools

### ISSUE THREAD

**Issue by profgiuseppe** [bio-tools/biotoolsregistry#149]
By searching by tool name or credits, the same tool is shown twice (same name, same version, same time since creation, same time since last update).
When added to the subdomain, both the entries get the "Added" status (checkbox).

**Comment by joncison** [comment]
pls. attach a screenshot so we can be sure what's happening

**Comment by profgiuseppe** [comment]
It seems that only some tools are affacted and not all of them (one screenshot shows both cases).

Example by searching for tool name:
![inps-md-duplicated](https://cloud.githubusercontent.com/assets/5399447/24461333/0824e95a-14a1-11e7-8702-cdc7a9431a9b.png)

Example by searching for credits (both duplicated and not duplicated are shown)
![bologna-duplicated](https://cloud.githubusercontent.com/assets/5399447/24461329/0539a690-14a1-11e7-8637-6a69c2f96f51.png)
