### ISSUE TITLE
affiliation for tools not owner by the one who creates the tool in registry

### ISSUE THREAD

**Issue by osallou** [bio-tools/biotoolsregistry#15]
When we add a new tool, tool will be prefixed by the affiliation.

If GenOuest user creates for example the emboss registry entry, tool will appear as GenOuest/emboss, though this tool is not owned by GenOuest. This can be confusing for users and could be an issue for upstream authors.

**Comment by joncison** [comment]
Concept of affiliations dropped, captured in `<credit>`
