### ISSUE TITLE
Search term available in drop-down but no search result

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#151]
see example below

![snip1](https://cloud.githubusercontent.com/assets/1506863/24465222/30b07eae-14a4-11e7-8ea0-c38c4b0469b8.PNG)
![snip2](https://cloud.githubusercontent.com/assets/1506863/24465233/37691e68-14a4-11e7-9258-f7f26c9bdaee.PNG)

**Comment by joncison** [comment]
another example is a search e.g. for "csc.fi" ... so I suspect it's to do with the non-alpha chars

**Comment by ekry** [comment]
This is fixed and deployed to dev.bio.tools:
https://dev.bio.tools/?page=1&q=%27University%20of%20Manchester,%20UK%27&sort=score&ord=desc
Will be moved to production in the next release.
