### ISSUE TITLE
Databases with version numbers :(

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#158]
Databases should never have version numbers ... so a systematic cleanup is needed (of everything where toolType == "Database portal"

**Comment by joncison** [comment]
![snip](https://cloud.githubusercontent.com/assets/1506863/24528813/38704668-15a0-11e7-9cde-ec881968634f.PNG)

**Comment by hansioan** [comment]
I specifically remember that the JASPAR database has versions, I am not sure about others though...
Perhaps an initial solution would be to remove version numbers for databases that have version numbers like "1" or "1.0". I see in the data that there are databases that have versions other than "1" or "1.0".

**Comment by hansioan** [comment]
Another example is Bgee:
https://bio.tools/tool/Bgee/version/13
http://bgee.org/

"""
2016-07-06 Release of Bgee version 13.2:
"""

**Comment by hansioan** [comment]
I know technically this is a tool that references a database rather than the actual database, but until we register the databases separately from tools, I think users add information that reflects the database version that is accessed via the database portal tool, rather than the actual version of the database portal too.

**Comment by joncison** [comment]
yeah, the JASPAR server is available in 2014 and 2016.  Bgee in contrast just has one server, the number 13 I guess refers to the underlying database, as you say.

In any case, we're not going to end up tracking versions, so I'd just strip them out in all cases except where we have multiple entries for a given named database portal (such entries will need consolidating)

**Comment by hansioan** [comment]
Removed version for 391 entries with toolType == "Database portal" that do not have multiple entries for a given named database.
