### ISSUE TITLE
Remove entries for different versions of a tool with trivial differences only

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#161]
See e.g. entries for https://bio.tools/tool/Kaiju/version/1.2

Once we have settled the definition of what is a valid new version (https://github.com/bio-tools/biotoolsregistry/issues/160) then invalid/trivial versions of tools should be systematically consolidated / deleted.

**Comment by joncison** [comment]
**NB**  while many cases (of trivial differences) should be automatically identifiable, many will not e.g. 
https://bio.tools/tool/ABySS/version/1.9.0
https://bio.tools/tool/ABySS/version/none

a range of checks will be needed to identify all cases

**Comment by joncison** [comment]
@hans - I think following our "spreadsheet from hell" exercise I can now close this?

**Comment by hansioan** [comment]
@joncison I think you can close this
