### ISSUE TITLE
DRCAT credit wrong

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#163]
The current type and role of DRCAT is wrong

![capture](https://cloud.githubusercontent.com/assets/1506863/24899087/9acfbc8e-1e8e-11e7-9666-1615c1bb7eff.PNG)

A systematic fix is needed 

Correct annotation is 
type=="Project"
role=="Documentor"

**Comment by hansioan** [comment]
Fixed all 194 credit instances for DRCAT.
