### ISSUE TITLE
Duplicate Topic annotation

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#164]
![capture](https://cloud.githubusercontent.com/assets/1506863/25167717/82e1ac68-24d8-11e7-81a0-7230cd573419.PNG)

needs a QA check followed by systematic fix (this goes for all fields if possible)

**Comment by hansioan** [comment]
Fixed entry, issue should stay open until the QA check is in place.

**Comment by hansioan** [comment]
Removed all duplicated topics from all tools. Won't close this until duplicated topics are detected at validation time.

**Comment by joncison** [comment]
@ekry will add the QC check to-do in due course
