### ISSUE TITLE
Duplicate credit (implement QC check, apply systematic fix)

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#167]
![capture](https://cloud.githubusercontent.com/assets/1506863/25218201/ec94a6aa-25a1-11e7-890a-b744c5da6a2a.PNG)

This in entry https://bio.tools/tool/ExpaRNA1/version/1.0.0

a systematic QA check is needed (then fixes)

**Comment by hansioan** [comment]
Fixed entry, won't close the issue until we have the QA check in place.

**Comment by joncison** [comment]
OK thanks, I updated the title accordingly

**Comment by hansioan** [comment]
Duplicated : see #129

**Comment by hansioan** [comment]
I think at this point all obvious credit duplicates (if not all entirely) are removed. Won't close this until the duplication detection is automated.

**Comment by joncison** [comment]
@ekry : is the QC check in place yet ??

**Comment by joncison** [comment]
@ekry - to close this issue we need to know if the QA check is in place - please respond.

**Comment by hansioan** [comment]
Fixed more duplicate instances, adding @piotrgithub1 to assignees until QC check in place.

**Comment by joncison** [comment]
This will be handled by biotoolsLint

**Comment by joncison** [comment]
This issue was moved to bio-tools/biotoolsLint#14
