### ISSUE TITLE
Links back to BioCatalogue are wrong (from Anne Wenzel)

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#175]
See e.g. 
https://bio.tools/tool/TcoffeeWS/version/1

I suspect a systematic error (i.e. all links back to BioCatalogue point to wrong place) - if so, I'd suggest the action for now is to simply remove all such links (unless an easy fix is possible).

**Comment by hansioan** [comment]
All BioCatalogue tool links back to biocatalogue.org are fixed.
