### ISSUE TITLE
Fix legacy of deprecated EDAM annotations in bio.tools

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#176]
Using ``replacedBy`` or (failing that being specified) the ``consider`` attribute defined on each deprecated EDAM concept.

This is urgent, because someone who tries to update entries containing deprecated annotations will be unable to do so (they'll get a validation fail)

From recent discussions, we settled upon the "silent fix" approach to deprecations (see https://github.com/bio-tools/biotoolsregistry/issues/98)

**Comment by joncison** [comment]
Bumping to urgent because we need to get this fixed for the next (Aug) release.

**Comment by joncison** [comment]
@hans - can I get an update on this please?

**Comment by hansioan** [comment]
Replaced all deprecated EDAM terms with the current terms of EDAM 1.18

1117 deprecated edam terms were automatically replaced using the `replacedBy` property
about 20 deprecated edam terms were manually replaced using the `consider` property
This is not a full solution as future deprecated terms will bring the same problems.

**Comment by joncison** [comment]
This is excellent.  Future deprecations will be handled automatically (https://github.com/bio-tools/biotoolsregistry/issues/98), so I think we can close this now?

**Comment by hansioan** [comment]
Updated to edam 1.19 , will close this and refer to #98 from now on.
