### ISSUE TITLE
BioCatalogue credits wrong

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#178]
![capture](https://cloud.githubusercontent.com/assets/1506863/25574671/679d11b2-2e48-11e7-8859-65fb881cc5e1.PNG)

A systematic fix (on all such credits) is needed:
creditType == Project
creditRole == Documentor

**Comment by hansioan** [comment]
Fixed all 304 BioCatalogue credit instances which now have creditType = Project and creditRole = Documentor and also they now all have the url `https://www.biocatalogue.org` (before some of them had NULL urls)
