### ISSUE TITLE
Search over Topics not working

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#180]
![capture](https://cloud.githubusercontent.com/assets/1506863/25575123/0c41ed34-2e4c-11e7-8f09-4ebd745ea1f8.PNG)

what I did was type "Proteomics", click "Topic"

A search for "Proteomics" in "Everything" does return results

**Comment by bug1303** [comment]
Same is true for Function.
E.g. starting to type:   RNA secondary structure prediction    in the Function lense, will suggest the term, but retrieve no results (https://bio.tools/?page=1&function=RNA%20secondary%20structure%20prediction&sort=score&ord=desc).
Searching for the same term in 'Everything' gives a number of results which actually have the term as Function (https://bio.tools/?page=1&q=RNA%20secondary%20structure%20prediction&sort=score&ord=desc).

**Comment by ekry** [comment]
This is fixed now for all attributes.
