### ISSUE TITLE
Bizarre search result for RNA interaction (from Anne Wenzel)

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#183]
An Everything search for: 
RNA interaction

produces results that are a bit inexplicable.

In contrast, an Everything search for: 
"RNA interaction"

produces meaningful results

It would be good, at least, to check why "MEME suite - cloud IFB" scores in the 1st rank for the 1st search above

**Comment by joncison** [comment]
This I think now fixed but waiting for Anne to confirm

**Comment by bug1303** [comment]
More or less as expected: A search for `RNA interaction` does retrieve more sensible things now as it seems, mostly containing RNA + interaction somewhere, but not necessarily as phrase. While `"RNA interaction"`retrieves tools containing the phrase. So far, so good.

However, the first result when sorted by "Updated" is https://bio.tools/seqcluster, which doesn't contain "interaction", but "interactive" -- I assume that's the flexibility allowed in the search, and supposedly has to be accepted to make the search function properly in general, ok.

When [sorted by score](https://bio.tools/?page=1&q=rna%20interaction&sort=score&ord=desc), https://bio.tools/forna ranks first, which also contains "interactive" not "interaction" as I see it. At least when sorted by score, I'd assume that exact match and possible even proximity would count higher than such partial matches.
(Another question might be if matches to a Topic/Function term count more or less than a match to the free text description, but for this the user can choose the different lenses specifically.)

**Comment by ekry** [comment]
A detailed round of critique is scheduled where we will look more in-depth into this. In the meantime an exact search can be performed using apostrophes, similar to how it's done on Google, which only returns results that exactly match the searched phrase, please see: https://bio.tools/?page=1&q=%27RNA%20interaction%27
