### ISSUE TITLE
Clean-up legacy search term in suggestions drop-down

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#185]
There are many cases where a suggested search term gives no results, e.g. "isb-sb.ch".  I suspect there is a legacy of (outdated) search terms being rendered here.  This needs cleaning up ASAP, then a system put in place to ensure that only relevant search terms (i.e. which will return results) is rendered.

**Comment by joncison** [comment]
Florian (de.NBI) says ... 

Not working:
  > enter "de."
  > wait for the auto-completion
  > click "de.NBI" from the suggestions
  > get nothing :(

@ekry : can you please look at a fix here ASAP ?

**Comment by ekry** [comment]
This is fixed and deployed to dev.bio.tools:
https://dev.bio.tools/?page=1&q=%27de.NBI%27
Will be moved to production in the next release.

**Comment by hansioan** [comment]
@joncison @ekry 
I can reproduce this, but the same error as with #244 , it happens because of the bad sorting, refresh 2 times or use the link:
https://bio.tools/?page=1&q=%27COILS%27&sort=score&ord=desc
and you do get the result for COILS

**Comment by joncison** [comment]
I close now (the sort-refresh bug still needs sorting)
