### ISSUE TITLE
Suppress rendering of top-level EDAM annotations

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#187]
![capture](https://cloud.githubusercontent.com/assets/1506863/25635195/3100ca8a-2f75-11e7-9b56-131fb46f1501.PNG)

this also goes for Topic of "Topic" ... both just make us look bad.  While we await meaningful annotations, they need to be suppressed from the view.

**Comment by joncison** [comment]
In these cases below the clean-up could be automated:
![capture](https://cloud.githubusercontent.com/assets/1506863/26311275/9e43358e-3efb-11e7-947f-17b01081b5b3.PNG)

In cases where we have only one annotation, cannot we just given "n/a" instead ?  cc @hansioan @ekry - a quick fix of this would be good.

**Comment by joncison** [comment]
Same case as for "Data" and "Format" - it just needs suppressing
![capture](https://cloud.githubusercontent.com/assets/1506863/26311409/1aa9412c-3efc-11e7-90c2-cf0ac82e56f5.PNG)

**Comment by joncison** [comment]
Another example (but for operation) where a quick / automated clean-up is needed cc @hansioan 
![capture](https://cloud.githubusercontent.com/assets/1506863/26575254/58c5c59a-451c-11e7-9149-979a536153ca.PNG)

**Comment by hansioan** [comment]
What I can do is remove "Topic" annotations from the DB. This means that if a tool has a "Topic" annotation, it won't have it anymore, it also means that if a tool only has the "Topic" annotation, it won't have anything else. 

Same goes for Operation and Data. The problem I have is that if I remove Operation and Data, I don't know how the interface will react because the tool cards have the Input(data, formats) -> Operation -> Output (data, formats) diagrams. I am afraid that if I make a DB remove then I might break the system since I'm not going through validation.

@ekry  What are your thoughts on the above.

**Comment by joncison** [comment]
Thanks - please do this (also for Format=="Format") once you have the all-clear from @ekry  (and let's please make any short-term hacks as necessary, because this is real grot and needs to go ASAP)

**Comment by hedi-ee** [comment]
Why not run these cases with EDAMmapper? While operation is harder to detect then for topic should be easier to add something meaningful.

**Comment by joncison** [comment]
Good suggestion.

@hansioan : let's put use of EDAMmapper into the workflow of the new student hires; at least for cases where we have a "top-level" annotation only

**Comment by hansioan** [comment]
Running EDAMmapper to fix topics might be a solution, but topics are the easier to fix and suppress rendering if need be.

There are ~1,300 tools which specifically have:
topic = Topic
operation = Operation
data type = Data
data format = Format

All these top level terms (at least the data type and format) should not have been added in the first place.

**Comment by joncison** [comment]
They were added in order to get the validation to pass so that we could get the entries in.  The solution in short term is to not show such annotations in bio.tools UI (if this is easy-ish to do).  In the longer term, to apply our curator manpower to annotate.

**Comment by joncison** [comment]
an EDAMmapper development is now led by EE, we could ask Ahto in our call today to look at this ...

**Comment by hansioan** [comment]
@joncison All instances of: 
- EDAM format == "Format"
- EDAM data == "Data" && EDAM format == "Format" 
- EDAM data == "Data" && no EDAM format at all

have been removed. All that is left is dangling EDAM operations == "Operations" and EDAM topic == "Topic"

@Ahto123 will use EDAMmapper to fix the "Topic" and "Operation" terms very soon. 

@joncison @ekry @Ahto123 
Do we still need to suppress rendering for "Operation" and "Topic" or replace it with some text like "Undefined Operation" / "Undefined Topic" or will EDAMmapper replace these fairly soon?

**Comment by joncison** [comment]
Fantastic. 

If we can suppress (not show) "Operation" and "Topic" in such cases - assuming this is fairly easy to do -
 then please do it.

Otherwise we wait for @Ahto123

**Comment by joncison** [comment]
From dev meeting : this under review, we're aiming to get non-default Topic and Operation annotations in, for all tools, ASAP (cc @Ahto123 ) - in which case this suprresion won't be needed ... but let's review each week.

**Comment by joncison** [comment]
@hansioan - can we now close this issue?  I think I'm right that all the "top-level" annotations are no longer shown / have been removed in the DB, and the registration interface no longer allows annotation with those terms. 

We can leave subsequent improvement by @Ahto123 of those entries for a different thread (cc @hedi-ee)

**Comment by hansioan** [comment]
@joncison @ekry I have removed the default ["Topic","Operation","Data","Format"] from the DB, but I've seen 2 tools registered in September that had topic = "Topic" and operation = "Operation". Not sure if a bug , or the check is not performed. I removed those annotations, so I cannot give you an example, but I have added some dummy tools and the "Topic" and "Operation" texts still render. 

What we also need to be careful with when we render are edge cases. For example, an EDAM data type = "Data" should be allowed if the format is specified and is not equal to "Format". 

Not sure what we should do if Operation = "Operation" when one or both of input and output data and or formats have meaningful annotations. As an example of how this might look is (don't know which looks better):
`Input: Sequence (FASTA) -> Operation -> Output: Sequence length (Text)`
or 
`Input: Sequence (FASTA) -> N/A  -> Output: Sequence length (Text)`

**Comment by joncison** [comment]
So I think there are two things:
* look into the possible bug / if the check is performed - with immediate action as necessary ( cc @ekry ) to suppress showing top-level annotations, respecting the edge cases
* I think "Operation" looks better than "N/A" in example given, however, "Unspecified operation" could be even better?

**Comment by joncison** [comment]
Fixed in Summary view, but not in function diagram view, see https://bio.tools/webbioc.  Tools with inputs and ouputs but no function should give the name of the tool in the middle box cc @baileqi @hmenager

**Comment by joncison** [comment]
@baileqi @ekry (cc @hansioan ) 

Look at:
![capture](https://user-images.githubusercontent.com/1506863/33147718-ba3e76bc-cfc0-11e7-8395-4d18670a6d84.PNG)

This (very obviously) is wrong.  The fix is:
* do not render "webbioc >" (in the red tab) 
* do not render the function diagram at all, in cases where we only have a high-level operation annotation

A fix for this is urgently needed, and cannot await a general clean-up of operation annotations (which is in-hands, see https://biotools.sifterapp.com/issues/156

**Comment by joncison** [comment]
@baileqi cc @ekry  the issue illustrated by https://bio.tools/webbioc needs fixing this week, please.  @hansioan is here to help as needed.

**Comment by joncison** [comment]
This problem not going away - so we fix this on the content side cc @hansioan

**Comment by joncison** [comment]
Vast majority of annotations with top-level EDAM terms have now been replaced with something more specific / useful.  Detection of future such cases is a concern of biotoolsLint (https://github.com/bio-tools/biotoolsLint/issues/10)
