### ISSUE TITLE
credit name is "see publication"

### ISSUE THREAD

**Issue by hansioan** [bio-tools/biotoolsregistry#190]
Many tools have credit name "see publication" along with different associated emails: 

https://bio.tools/tool/HX-Express/version/none

I think this looks bad... We should either replace the "see publication" text with a name based on the supplied email or at least remove the "see publication" initially.

**Comment by joncison** [comment]
Agreed.  For now, just remove "see publication".

**Comment by hansioan** [comment]
I removed the "see publication". I think at this point all obvious credit duplicates (if not all entirely) are removed. Won't close this until the duplication detection is automated.

**Comment by joncison** [comment]
eh?  do you mean "see publication" is now in QC (it probably should be)

**Comment by hansioan** [comment]
No it isn't in the QC, I don't know if it should be. I just wanted to say that I've fixed the "see publication" stuff. Perhaps I should close this, we have the duplication and other types of credit problems in other issues
