### ISSUE TITLE
EMBOSS tools credits

### ISSUE THREAD

**Issue by hansioan** [bio-tools/biotoolsregistry#192]
@joncison 
Many EMBOSS tools have the credit:

`See http://emboss.open-bio.org/html/use/pr01s01.html`

The page at the above link does list a fairly large number of contributors. 

Is it acceptable to have this "see link" credit?

**Comment by joncison** [comment]
I think the correct credit would be name=="EMBOSS Contributors" and URL as above.

**Comment by hansioan** [comment]
Fixed all instances with wrong credit
