### ISSUE TITLE
Add Score to search results

### ISSUE THREAD

**Issue by lexnederbragt** [bio-tools/biotoolsRegistry#193]
By default, search results are sorted on 'Score'. The actual score is not listed in the search results page, nor can it be selected as a column in the Grid output format.

**Comment by joncison** [comment]
score is now dropped in latest version https://bio.tools/

**Comment by bug1303** [comment]
A simple (ctrl+R) refresh of the page after a search, however, brings back the Sort by "Score" button... 

Also I'd say, sorting by "Score" should be the default, given that it actually produces the expected results (i.e. most relevant first), although I know that is not exactly trivial to achieve.

**Comment by joncison** [comment]
A better label could be "Relevance" and I agree it should be the default sort order.  Pascal from ELIXIR Hub also raised this yesterday cc @ekry

**Comment by hansioan** [comment]
Sorting by score is the default, as long as there is a search. @joncison and I agree that we agree not to render the score value anywhere as it does not provide much value.
