### ISSUE TITLE
Preserve subdomain metadata for subdomains with no tools

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#194]
Florian (de.NBI) says ... "Next we moved on and did add an existing tool to the subdomain. Perfect. Then we removed the tool as a test. What happens is, that the subdomain will still exist but all other entries (title, subtitle & desription) will be lost. Apparently these information can only be stored with at least one associated tool to the subdomain. We did run into this problem a number of times, and it is quite disturbing having to copy+paste everything all over again :/"

**Comment by ekry** [comment]
This is fixed now.
