### ISSUE TITLE
Search for "Output: Sequence alignment" returns no hits

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#197]
The faceted search (on output) fails:
![capture1](https://user-images.githubusercontent.com/1506863/27508192-cb3e1a68-58d7-11e7-9e95-dd6d3d655fd5.PNG)

Wherease the "Everything" search works:
![capture2](https://user-images.githubusercontent.com/1506863/27508195-d724be68-58d7-11e7-98e2-ac766d1a2152.PNG)

**Comment by joncison** [comment]
Same deal when searching for formats on output:
![capture1](https://user-images.githubusercontent.com/1506863/27633040-8ddb46a2-5bf5-11e7-98b5-9f27dfa345e3.PNG)
![capture2](https://user-images.githubusercontent.com/1506863/27633049-947a7bfe-5bf5-11e7-84e5-973a9297c7cc.PNG)

**Comment by krab1k** [comment]
In some cases, even "Everything" doesn't work as expected.

![image](https://user-images.githubusercontent.com/16164737/27852893-21af9a98-6161-11e7-9cee-412876c9c4b8.png)

![image](https://user-images.githubusercontent.com/16164737/27852911-3757efee-6161-11e7-9624-51a32e46d2bf.png)

**Comment by joncison** [comment]
Also via API, this fails:
https://bio.tools/?page=1&output=HTML&sort=score&ord=desc

Input searches seem to be working, so this must be some silly little bug

**Comment by ekry** [comment]
This is fixed and deployed to dev.bio.tools:
https://dev.bio.tools/?page=1&output=%27Sequence%20alignment%27
https://dev.bio.tools/?page=1&q=%27Repeat%20Explorer%27
https://dev.bio.tools/?page=1&output=HTML&sort=score&ord=desc
Will be moved to production in the next release.
