### ISSUE TITLE
N/A publications

### ISSUE THREAD

**Issue by hansioan** [bio-tools/biotoolsRegistry#200]
The curation of tools which had no information about publication is done. At this point all tools (except the ones that were added after I provided the students with the list if any…) either have a publication id OR are marked as not published. Now that we now that some tools are not published, what do we do with this information? Should we have an N/A value where we know there is no publication? How should this be represented in the DB? Perhaps the web interface should provide a message like “No publication found” for this N/A publication tools. What do you think? I think we should do something with the information about a tool NOT having a publication.

**Comment by joncison** [comment]
This is valuable information and it's essential we record it, but it has implications for biottoolsSchema, the bio.tools JSON model, API and UI.

For now I propose a quick hack (a new field, whatever is easiest) to store the information in the database.

In the longer term we need:
* First, settle how this is handled in the schema, see https://github.com/bio-tools/biotoolsSchema/issues/82
* Implement the corresponding changes in bio.tools back-end & API
* Implement the necessary changes in the bio.tools UI - this may be harder to do than it sounds, and it should certainly include some way of indicating clearly (maybe a tooltip in some cases) the information was searched for but not available at the time of edit

I don't think we have time to do any of this this Summer, but it certainly needs to be done.

cc @ekry

**Comment by hansioan** [comment]
@joncison @ekry What I suggest if we are doing a hack is to have the N/A value in all 3 publication id fields (i.e. pmid , pmcid and doi). So 3 N/As would mark it as no publication has been found. What do you think?

**Comment by joncison** [comment]
no ... that would break the syntactic constraints / validation / XML facets of those fields

we could do such a thing where (for other attributes) we have an enum - which could simply be extended to include "n/a"

**Comment by hansioan** [comment]
OK, the only thing is that we need to be quick about it so I can get these things into the DB and produce the stats.

**Comment by joncison** [comment]
I'd suggest just create two new fields:
* notAvailable (boolean): "true" if not publication not found
* notAvailableDate (data): i.e. date the above was set true

but @ekry should call the shots here

**Comment by joncison** [comment]
on 2nd thoughts, we could in principle (at least in biotoolsSchema XSD) trivially extend the facet to allow for "n/a", "Not available" or whatever.  

Whether we _should_ I seriously doubt:  folk (consuming bio.tools data) might reasonably expect e.g. a DOI field to only contain a syntactically valid DOI.

**Comment by joncison** [comment]
The immediate action is to record not available (and date) in the back-end.  We can do a proper implementation (involving scheme & UI change, etc.) later.

**Comment by joncison** [comment]
@hansioan - please close this (if you agree) that we can
