### ISSUE TITLE
weird (out of enum) licenses

### ISSUE THREAD

**Issue by redmitry** [bio-tools/biotoolsregistry#201]
Hello all,

There are many licenses in data that are from the old records and don't comply with Schema 2.0 enumeration. It would be great to fix them in a batch.

for instance:
"GNU General Public License v2"  =>  "GPL-2.0"
"GNU General Public License v3"  =>  "GPL-3.0"

**Comment by joncison** [comment]
agree - see https://github.com/bio-tools/biotoolsregistry/issues/125 and bumping the priority there
