### ISSUE TITLE
Remove duplicated entries for Muscle

### ISSUE THREAD

**Issue by veitveit** [bio-tools/biotoolsRegistry#203]
There are currently 3 entries.

Needs to be removed:
https://bio.tools/tool/muscle/version/3.12.0

We need to decide how to merge the entries coming directly from automatic upload from EBI and Bioconductor. There has to be an automatic way for this in the future.

**Comment by joncison** [comment]
All duplicates need to be gone certainly by end of August, so we can get unique IDs and index the whole site.  Hans and I have a big sheet were working through.  We did contemplate tooling for it, but no one had bandwidth to develop it :-/
