### ISSUE TITLE
Fix broken credits from BioMedBridges

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#204]
![capture](https://user-images.githubusercontent.com/1506863/28016908-5d09b950-656e-11e7-9ab8-4dd043e84cb0.PNG)

For BioMedBridges 

typeEntity=="Consortium"
typeRole=="Documentor"

systematic fix needed (there may be several such credits)

**Comment by joncison** [comment]
This now needs to be fixed ASAP, the annotation is just wrong.

**Comment by hansioan** [comment]
@joncison BioMedBridges are also listed in some cases as "Funding agency" -> "Contributor". Should I also replace those?

**Comment by joncison** [comment]
yes please ... it was a consortium not a funding agency

**Comment by hansioan** [comment]
done, closing issue
