### ISSUE TITLE
Labelling Tool Cards based on broken homepageURL

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#207]
As agreed, need to:
1. systematically identify all broken homepageURL links (see https://github.com/bio-tools/biotoolsregistry/issues/88) - presumably this is available in the internal QC report?
2. repair broken links 
3. _or_ if the website cannot be found, delete the entry (if owned by bio.tools admin) or contact the owner (otherwise)

**Comment by joncison** [comment]
I suggest a coordinated action with  @Ahto123 and Tomas.

**Comment by hansioan** [comment]
The approach we take on homepages is that we will periodically query homepages and mark them accordingly. A homepage status can have the values:
- 0 down
- 1 up
- 2 permanently down (manual inspection and decision is required for this)

An automatic process will check the URL (for status 200 OK) and update the status based on the following:

- if the homepage status is 1 in the DB, but the current query does not return 200 OK, change the homepage status to 0
- if the homepage status is 0 in the DB, and the current query returns 200 OK, change the homepage status to 1
- if the homepage status is 2 (after being manually inspected and set to 2), but the query returns 200 OK then set it back to 1 anyway, but if it's still 0, leave it at status 2
- it is important that at the time of changing a status after a query to also include the timestamp at which the query was done. This is useful in case the homepage status is 0 and a future query still returns status of 0, case in which we would keep the status 0 with the oldest timestamp (i.e. when the homepage was first seen as down)
- perhaps it might be a good idea to also keep data on a "latest time" when a homepage was queried, in addition to the time it first went down. So 2 fields: "downSince" and "latestCheck".

**Comment by hansioan** [comment]
A note on this are url redirects:
For example if the tool has the homepage http://phylobench.vital-it.ch/raxml-bb/ it actually redirects to https://embnet.vital-it.ch/raxml-bb/ , but the HTTP status is `301 Moved Permanently`. The second url is fine in this case.
On the other hand the tool https://bio.tools/muplex has the homepage http://apps.diatomsoftware.com/muplex/html/MuPlex.html which redirects to https://www.hugedomains.com/domain_profile.cfm?d=diatomsoftware&e=com with a status code of `302 Found`. 
This means that "correct" redirects to good homepages will be seen as down. If we do decide to accept redirects it could be the case that we get bad redirects.

**Comment by joncison** [comment]
Recommend to:
* treat `301 Moved Permanently" exactly like `200 OK`.
* treat `302 Found` in same way as other bad / unresolvable URLs

**Comment by hansioan** [comment]
Also an example of a retired tool is https://bio.tools/kindock
for which the homepage status is 200, but it just contains a message saying that the tool is obsolete.

**Comment by redmitry** [comment]
In OpenEBench we keep track of metrics changes, so one would be able to see historical metrics change for the tool:
https://elixir.bsc.es/metrics/log/{ID}/{path}
where {ID} is our ID taken from bio.tools in a way : {**id**}/{**type**}/{**authority**}
**id** = bio.toos:toolID - bio.tools **toolID**
**type** = shortNames form bio.tools **toolType** ("cmd", "web", "rest", "soap" ...)
**authority** = the institution that owns the service. Here we use a hostname from bio.tools **homepage**
**path** = json pointer to the property (for instance: project/website/operational)
example:
https://elixir.bsc.es/metrics/log/bio.tools:pmut/cmd/mmb.irbbarcelona.org/project/website/operational
note that the current state (checked periodically) may be obtained directly:
https://elixir.bsc.es/metrics/bio.tools:pmut/cmd/mmb.irbbarcelona.org/project/website/operational

Cheers,

Dmitry

**Comment by redmitry** [comment]
Hello,
We are working on the benchmarking and just changed the url:
https://openebench.bsc.es/monitor/metrics/bio.tools:pmut/cmd/mmb.irbbarcelona.org/project/website/operational
https://openebench.bsc.es/monitor/metrics/log/bio.tools:pmut/cmd/mmb.irbbarcelona.org/project/website/operational

This supposed to be final.

Cheers,

Dmitry

**Comment by joncison** [comment]
The issue is now to label the Tool Cards appropriately when a broken link is detected (in future by biotoolsLint, see bio-tools/biotoolsLint#9)

See:
#230
#88

**Comment by hansioan** [comment]
Perhaps a good solution is a combined approach of checking / updating homepage/link status once a day and checking / rendering homepages based at tool load as well.

**Comment by joncison** [comment]
"link" meaning any URL, not just homepage URL

**Comment by hansioan** [comment]
Perhaps once can use
https://updown.io/api
