### ISSUE TITLE
Subdomain URL does not rewrite correctly

### ISSUE THREAD

**Issue by profgiuseppe** [bio-tools/biotoolsregistry#211]
Hello,
if I try accessing a subdomain, i.e.

[https://bologna.bio.tools/](https://bologna.bio.tools/)

I'm not redirected to the correct query, i.e.

[https://bio.tools/?domain=bologna](https://bio.tools/?domain=bologna)

and then, as you can see, I get a different list of tools.
Tested with both Chrome and Firefox.

**Comment by joncison** [comment]
@ekry or @baileqi will you please take a look at this?

**Comment by ekry** [comment]
The underlying mechanism for this is fixed on dev.bio.tools, but the new interfaces do not yet support branding: http://bologna.dev.bio.tools (please ignore the certificate warning, it's due to this being the dev server). We will add branding support before the next release.

**Comment by profgiuseppe** [comment]
Given that the type of certificate cann't be added to the exception list, I'm unable to check it on dev.bio.tools. We will see when you deploy the next release.

**Comment by joncison** [comment]
Please test this for yourself (on https://bio.tools, not the dev server), works for me but please confirm this is good for you (then we'll close)

**Comment by profgiuseppe** [comment]
Works fine now, thank you.
