### ISSUE TITLE
PomBase assembly converter : wrong homepage URL

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#220]
http://genomebrowser.pombase.org/Schizosaccharomyces_pombe/Tools/AssemblyConverter?db=core

This probably goes for other tools in the PomBase suite

**Comment by hansioan** [comment]
This problem can be found for suites see:
https://bio.tools/?page=1&q=assembly%20converter&sort=score&ord=desc

This is tracked in the issue #243
