### ISSUE TITLE
Variant Effect Predictor : wrong homepageURL

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#221]
https://bio.tools/tool/variant_effect_predictor/version/1

**Comment by redmitry** [comment]
Should we add a ticket for every broken homepage?
There are probably 50 pages....

**Comment by joncison** [comment]
There are some that are wrong (point to wrong place) : please create tickets for these.

I gave up adding tickets for broken homepageURLs - instead, there needs to be a systematic check & repair of these (I understand the bio.tools QC already checks, so if this is right, they just need to be fixed.  cc @hansioan

**Comment by redmitry** [comment]
OK. I will prepare the entire list - I have it in a log, but have to filter.

**Comment by joncison** [comment]
Cool ...  in case this is not already readily available in bio.tools QC, please post it in a separate thread.

**Comment by redmitry** [comment]
Technically the state is updated every 6 hours:
https://elixir.bsc.es/elixibilitas/biotools/bio.tools:Entrez/metrics/project/website/operational
probably we need another property, something like "last_time_seen"

**Comment by joncison** [comment]
What do I substitute for ``Entrez`` above?

**Comment by redmitry** [comment]
https://elixir.bsc.es/elixibilitas/biotools/{id}/metrics/[path]
where {id} is "bio.tools:{toolID}[:version]"

**Comment by jlgelpi** [comment]
+1
It probably should be extended sa
status: ???
last_time_active: ???

Eventually, also
max_activity_period: ??
