### ISSUE TITLE
EVA wrong homepageURL

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#227]
https://bio.tools/tool/EVA/version/none

homepageURL should be http://pdg.cnb.uam.es/eva/

**Comment by hansioan** [comment]
@joncison 
EVA here is short for European Variation Archive and the homepage should be:
https://www.ebi.ac.uk/eva/

I think the EVA at
http://pdg.cnb.uam.es/eva/
is something else
