### ISSUE TITLE
Remove 'doi:' prefix from DOIs

### ISSUE THREAD

**Issue by khillion** [bio-tools/biotoolsRegistry#229]
I have noticed that some of the DOIs (e.g. Primary publication for https://bio.tools/tool/pepwindow) have their publication IDs with a prefix: 
```json
{
     "pmcid": null,
     "pmid": null,
     "doi": "doi:10.1016/S0168-9525(00)02024-2",
     "type": "Primary"
}
```
That would be convenient if either when registering, this would not be allowed **or** that bio.tools would automatically reformat the ID correctly. What do you think ?

**Comment by hansioan** [comment]
The fact is that the links do work without and with the doi part. 
I think in the end they should not have a DOI, because we only need the part after the "doi:" to create the link.

**Comment by khillion** [comment]
Indeed links work, I think the resolver somehow accept both.
However, for instance, I am performing mapping between Galaxy Tools and bio.tools entries based on DOIs and realized that some were not able to map because of that. Of course a simple hack is easy to set up from my side to bypass this issue. I think that in the end, it would be cleaner if IDs on bio.tools would correspond only to exact IDs and nothing more.

**Comment by joncison** [comment]
As I understand, the "doi" prefix is optional in the DOI syntax (both with and without forms are valid DOIs).  

So we should accept both, but I agree it would be cleaner / helpful to just render one style of them (i..e without the prefix).  The cleanest way would be to transform the value upon registration or edit.

**Comment by joncison** [comment]
@hansioan, @khillion - I've changed my mind; and will enforce (in the next release of biotoolsSchema) specification of DOIs only **without** the "doi" prefix, to make the data more tractable.  

For the same reasons, I'll drop support for the "PMID:" prefix of PMIDs.  PMCIDs **must** keep their prefix though.

A bio.tools content refactoring is needed (cc @hansioan @ekry) - I made a note of this so we can revisit this later this week.

**Comment by hansioan** [comment]
Data is ok now, we still need a final check after the release.

**Comment by hmenager** [comment]
fix confirmed

**Comment by joncison** [comment]
cc @khillion
