### ISSUE TITLE
Allow reuse of a query

### ISSUE THREAD

**Issue by khillion** [bio-tools/biotoolsRegistry#233]
When you have a query done (e.g. "Everything:bowtie2"), it is not possible to relaunch the query by pressing "enter". The query is saved but it is not possible to use it, you need to remove the query and retype it.

**Comment by hansioan** [comment]
@khillion 
I am not sure what you mean by relaunching the query. I don't see why you would want to relaunch the query since there won't be any new information. 
Also one can always refresh the page.

**Comment by khillion** [comment]
Hey @hansioan, I think it has been fixed. I am not sure what I meant at this time but it seems to be good now!
