### ISSUE TITLE
2. Access to docs link when not logged in

### ISSUE THREAD

**Issue by dansondergaard** [bio-tools/biotoolsRegistry#236]
With the new menu design for bio.tools, it's no longer possible to access the documentation from the menu when not logged in. This is rather annoying when you accidentally get logged out or have to access the docs from a new machine.

It would be great if the docs link was still accessible when logged out.

From a slightly larger perspective, I think that the "Menu" menu is a bad idea. It forces the user to click twice to get to "Add Content", which is one of the main purposes of the site, and the docs become harder to find. I think it would be a significant improvement to replace the "Menu" menu with three icons: one for "Add Content" and one for "Manage subdomains" (these would only show when logged in). The third icon would be the famous question mark, linking to the docs (always visible).

Just my 2 cents :-)

**Comment by joncison** [comment]
Firmly agree on the 1st point ("Docs" link should always be there) - this is a bug.

As for the second, I'm not sure.  It depends whether we'll want more options in future, e.g. for "Support" or whatever (e.g. https://github.com/bio-tools/biotoolsregistry/issues/146).  If we have quite a few items they might be best put under a menu.

**Comment by dansondergaard** [comment]
In case something like that needs to be added, it would be fine to have a "?" icon which opened a dropdown menu with "Documentation" and "Support" items, I think. It's OK to group things, but the "Menu" menu doesn't give any indication of what is to be found when clicking it.

I've never seen a website with a menu called "Menu", it seems like bad usability design.

**Comment by joncison** [comment]
Agree "Menu" is just strange.  I also find "?" a bit odd (perhaps this is just me).  But anyhow, yes, this can / should be improved cc @ekry

**Comment by dansondergaard** [comment]
The question mark icon is quite often used to mean help/support (e.g. in the upper right corner of Facebook). But yes, there's definitely other options to consider.

**Comment by joncison** [comment]
@dansondergaard : a designer is joining the team soon and can advise us on best option re "Menu", "?" etc.

**Comment by joncison** [comment]
@baileqi cc @hansioan : can we please get a quick fix to include a menu that is always shown, _i.e._ not just to logged on users?  The menu could be called "Help" and include:
* Docs (link to https://biotools.readthedocs.io/en/latest/ )
* Report issue (link to https:://github.com/bio-tools/biotoolsregistry/issues
* Contact us (link to mailto:registry-support@elixir-dk.org)

We can then rename the existing menu labelled "Menu" (visible to only logged-on users) to "Actions" (which is, in fact, what the menu would then include).

This are trivial changes that would have a **big impact**, so please take action ASAP. Bumping the priority accordingly.

**Comment by baileqi** [comment]
Done.

**Comment by joncison** [comment]
See https://dev.bio.tools

Not quite done :)  Still need:
* Contact us (link to mailto:registry-support@elixir-dk.org) - which for now could go at the bottom.

**But** I think it would be much cleaner if - rather than a "?" at the top and two links at the bottom - to have a single menu called "Help" with "Docs, Report Issue, Contact Us" items as per the original request.   In this scenario, the exist "Menu" should be relabelled as "Actions".

cc @hans for a 2nd opinion.

**Comment by joncison** [comment]
Original issue is fixed, but still scope to improve the menu (see https://github.com/bio-tools/biotoolsRegistry/issues/358)

**Comment by joncison** [comment]
Original issue is fixed, but still scope to improve the menu (see https://github.com/bio-tools/biotoolsRegistry/issues/358)
