### ISSUE TITLE
Page design - Logo

### ISSUE THREAD

**Issue by PascalKahlem** [bio-tools/biotoolsRegistry#239]
Hi, 
the ELIXIR logo on the top-left of the page should link to www.elixir-europe.org
I also suggest to add a link to a documentation.

Best regards,
Pascal

**Comment by joncison** [comment]
really that logo should be replaced with a bio.tools logo, because folk (at least me :) use it as a "Home" button.  And then we display the ELIXIR logo prominently elsewhere, with the link as suggested.  cc @ekry 

you can find the docs link via the "Menu" button

**Comment by joncison** [comment]
now replaced with ELIXIR-branded bio.tools logo
