### ISSUE TITLE
Inexplicably top hit for search for "blast"

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#244]
The top hit returned is "IRESite" and I don't understand why (see attached)

We can guarantee that people will use this search term to test the registry, so this needs fixing ASAP
![capture](https://user-images.githubusercontent.com/1506863/31657476-5ea89d20-b326-11e7-89bd-bdbfcfce1d96.PNG)

**Comment by hansioan** [comment]
@joncison @ekry 
The issue is still with the sorting of entries based on score, if you refresh the blast search 2 times or go to the link:
https://bio.tools/?page=1&q=blast&sort=score&ord=desc
you will see that it works

**Comment by joncison** [comment]
Update from talking to Pascal ... the "Score" button also disappears when you "Refresh" .... @ekry fix needed ASAP please

**Comment by hansioan** [comment]
the issue is with sorting and some missing arguments from the search URL. One way to get past this issue until it's properly fixed is to refresh 2-3 times. It will work then

**Comment by joncison** [comment]
cc @baileqi @hansioan  - this appears to be fixed (awesome!) ... pls. verify and close

**Comment by hansioan** [comment]
Looks good to me, closing issue
