### ISSUE TITLE
Improved annotation for Glycomod

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#247]
From SIB annotations, to be merged into what we have:

	<tool>
		<summary>
			<name>GlycoMod</name>
			<toolID>glycomod</toolID>
			<description>Predict possible oligosaccharide structures that occur on proteins from their experimentally determined masses. The program can be used for free or derivatized oligosaccharides and for glycopeptides.</description>
			<homepage>http://web.expasy.org/glycomod/</homepage>
		</summary>
		<function>
			<operation>
				<uri>http://edamontology.org/operation_0416</uri>
				<term/>
			</operation>
			<operation>
				<uri>http://edamontology.org/operation_0417</uri>
				<term/>
			</operation>
			<operation>
				<uri>http://edamontology.org/operation_2479</uri>
				<term/>
			</operation>
		</function>
		<labels>
			<toolType>Command-line tool</toolType>
			<topic>
				<uri>http://edamontology.org/topic_0080</uri>
				<term/>
			</topic>
			<topic>
				<uri>http://edamontology.org/topic_0121</uri>
				<term/>
			</topic>
			<topic>
				<uri>http://edamontology.org/topic_0122</uri>
				<term/>
			</topic>
			<topic>
				<uri>http://edamontology.org/topic_0601</uri>
				<term/>
			</topic>
			<topic>
				<uri>http://edamontology.org/topic_3520</uri>
				<term/>
			</topic>
		</labels>
	</tool>

**Comment by hansioan** [comment]
Same as #246 , the tool type == Command-line tool is wrong, but in this case it is a Web application. Updated with the rest of the annotation.
