### ISSUE TITLE
URGENT: Implement and show statistics about bio.tools

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsregistry#25]
## Numbers over time (can be in 1 or 2 graphs):
- number of records over time
- of EDAM annotations
- of size of entries
- of number of operations
- of number of users(!), accounts(!), affiliations(!), institutions, ORCIDs, DOIs, PMIDs, collections, etc !!!
- of countries!!! How? (See also next)
## Geographical distributions and growth over time!

Somehow...

**Comment by matuskalas** [comment]
## Also indicate events(?)
Hack merge with the google calendar somehow?

**Comment by matuskalas** [comment]
## + Update model (2.0) to enable good statistics
Geography, institutes, persons, ...

**Comment by joncison** [comment]
Emil and I discussed this in DK - see attached.
[RegistryMetrics.pptx](https://github.com/bio-tools/biotoolsregistry/files/129713/RegistryMetrics.pptx)

**Comment by joncison** [comment]
See also https://github.com/bio-tools/biotoolsregistry/issues/113

Most of this is done in https://bio.tools/stats.  Remaining bits added to above issue

**Comment by joncison** [comment]
Events are listed: http://biotools.readthedocs.io/en/latest/events.html
