### ISSUE TITLE
Improved annotation for MAFFT - EBI

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#251]
```
	<tool>
		<summary>
			<name>MAFFT - EBI</name>
			<toolID>mafft-ebi</toolID>
			<description>MAFFT (Multiple Alignment using Fast Fourier Transform) is a high speed multiple sequence alignment program.</description>
			<homepage>http://www.ebi.ac.uk/Tools/msa/mafft/</homepage>
		</summary>
		<function>
			<operation>
				<uri>http://edamontology.org/operation_0347</uri>
				<term/>
			</operation>
		</function>
		<labels>
			<toolType>Command-line tool</toolType>
			<topic>
				<uri>http://edamontology.org/topic_0121</uri>
				<term/>
			</topic>
			<topic>
				<uri>http://edamontology.org/topic_0622</uri>
				<term/>
			</topic>
		</labels>
	</tool>
```

**Comment by hansioan** [comment]
I think the name MAFFT (EBI) as it is now adheres to the naming convention stated in the curator guide, whereas MAFFT - EBI would break that. 
I will also change the id from the current one `mafft` to the suggested one `mafft-ebi` in light of having the canonical tool `MAFFT` annotated in bio.tools #254

**Comment by hansioan** [comment]
The operation term:
http://edamontology.org/operation_0347
is deprecated, I used the replacedBy term in the annotation

Added the annotations, the tool type == Command-line tool is wrong, it is a Web application
