### ISSUE TITLE
Improved annotation for MUSCLE - EBI

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#252]
```
	<tool>
		<summary>
			<name>MUSCLE</name>
			<toolID>muscle</toolID>
			<description>Multiple alignment server</description>
			<homepage>http://www.ebi.ac.uk/Tools/msa/muscle/</homepage>
		</summary>
		<function>
			<operation>
				<uri>http://edamontology.org/operation_0347</uri>
				<term/>
			</operation>
		</function>
		<labels>
			<toolType>Command-line tool</toolType>
			<topic>
				<uri>http://edamontology.org/topic_0121</uri>
				<term/>
			</topic>
			<topic>
				<uri>http://edamontology.org/topic_0622</uri>
				<term/>
			</topic>
		</labels>
	</tool>
```

**Comment by hansioan** [comment]
I will update the EBI version of this tool with the annotation.
The EBI annotation is actually pretty good, don't know if this helps in any way(I think it might be wrong, especially Proteomics topic, not sure if Genomics topic is correct either), but will add some of it.
The tool type == Command-line tool is wrong, it is a Web application.

**Comment by hansioan** [comment]
@joncison in fact I think all of it is wrong, will not add it to the annotation

**Comment by joncison** [comment]
OK, good.  I just pasted in the supplied XML, you've spotted that some things are wrong e.g. the tool types.
