### ISSUE TITLE
Draft/temporary records

### ISSUE THREAD

**Issue by OlivierCollin** [bio-tools/biotoolsregistry#273]
Hello, 
The possibility to save draft or temporary records could be interesting. 
For example, I started to insert information for a new resource before realizing that all mandatory information was not available. 
I thought I could save it in order to come back later but it does not seem to be the case and I lost my work. 
Best regards, 
Olivier

**Comment by hansioan** [comment]
We will soon change the fields that are mandatory to include a few, so it will be easier to save your work after you've filled in less fields than now

**Comment by OlivierCollin** [comment]
OK, but could it be possible to tag a record as a work in progress ? 
Of course there could be conflicts that should have to be resolved if two persons edit the same tool one of them having tagged his entry as a wip leaving the other person unaware of the previous entry.

**Comment by joncison** [comment]
We'll discuss this at our next dev call and get back to you  here Olivier.

PS. as Hans said, soon-ish you'll only need to specify tool name, short description and homepage URL (although such entries will not be made visible until a bit more is provided)

**Comment by joncison** [comment]
Hi @OlivierCollin - for now, we will not do this.  Although a "sandbox" such as you describe could be useful, the cost :: benefit means we can't do it now.  Hopefully once the new schema is implemented (very soon) the lower information requirement should make it much easier to generate basic valid entries, which you can revisit to improve upon later.

cc @hansioan @ekry
