### ISSUE TITLE
Publication mandatory or not ? 

### ISSUE THREAD

**Issue by OlivierCollin** [bio-tools/biotoolsRegistry#274]
Hello, 

I was wondering if the publication field is mandatory. 
The behaviour of the submission interface when saving a record indicates the publication as a missing info. However, I was able to save the record (I initially thought this was a draft functionnality) and now it is available in the registry without the publication reference. 

Best regards, 
Olivier

**Comment by joncison** [comment]
Hi Olivier

This is a moving picture.  In future registrations will be accepted at "Sparse" level of information (https://github.com/bio-tools/biotoolsSchemaDocs/blob/master/information_requirement.rst) but will not become visible until "Basic details" (at least) are provided.   This will all be reflected in the UI.   There will be a mechanism to specify a publication is "not available" (i.e. for unpublished tools) which will allow the tool to qualify for "Basic details", i.e. be visible on the site.  

Still, the star on the publication field needs to go ASAP to reflect the current state cc @ekry @hansioan FTI.

**Comment by bagnacan** [comment]
Until the issue is solved, it is possible to circumvent the validation error by selecting a publication type, leaving all other fields blank

**Comment by joncison** [comment]
In the next release (for biotoolsSchema 3.0.0 - out soon) publication is not mandatory, so this issue goes away

**Comment by joncison** [comment]
cc @OlivierCollin @bagnacan
