### ISSUE TITLE
Not all search results are shown in the table/grid view

### ISSUE THREAD

**Issue by bug1303** [bio-tools/biotoolsregistry#276]
A search for ['RNA structure prediction'](https://bio.tools/?page=1&q=%27RNA%20structure%20prediction%27&sort=score&ord=asc) yields 25 tools (at least that's what's shown on the right end of the search field), however only one page with 10 tools is listed (can not move on to next page). By changing the sorting, I can see that there are in fact (at least) 25 tools. Changing the URL from page=1 to page=2 results in some flickering, but no stable rendering.
Similarly, a search for ['Protein secondary structure comparison'](https://bio.tools/?q=%27Protein%20secondary%20structure%20comparison%27&sort=score&ord=asc) supposedly yields 47 tools, but only shows 20 of them on 2 pages.

**Comment by hansioan** [comment]
weird behaviour on page 2 and 3
https://bio.tools/?page=2&q=%27RNA%20structure%20prediction%27&sort=score&ord=desc
https://bio.tools/?page=3&q=%27RNA%20structure%20prediction%27&sort=score&ord=desc

**Comment by joncison** [comment]
@baileqi what's the status?  Let's close this as soon as fix is in production.

**Comment by baileqi** [comment]
I will try to investigate it now.

**Comment by joncison** [comment]
this is same bug as the FOD issue (https://github.com/bio-tools/biotoolsregistry/issues/287) - I close this now.  Good work @baileqi !!
