### ISSUE TITLE
Usability issue: Validate button & invalid records

### ISSUE THREAD

**Issue by sduvaud** [bio-tools/biotoolsRegistry#277]
There should be a more obvious way for the user to understand that his/her record is invalid.
Indeed, for now, the "Validate" button remains green and a small cross replaces the usual small tick. This not noticeable enough, and confusing for most of the users who usually think that a green button means "All ok".

**Comment by joncison** [comment]
Agreed - this can (and needs) big improvement, not just in ways above.  Likely this will be addressed when we make other changes in support of the information standard (https://github.com/bio-tools/biotoolsSchemaDocs/blob/master/information_requirement.rst) : the plan is to accept registrations at "sparse" level but not show them until "Basic details" are provided.  So we need to make this very plain (along with validation errors) in the UI.

**Comment by joncison** [comment]
@sduvaud, the fix @hansioan and I agreed / made:
1. an invalid record gets the text "There are validation errors: please fix values shown in red.  See JSON tab for a list of all errors."
2. the "Validate" and "Save" buttons are given with red crosses and borders to indicate the invalid state.

To be released soon

**Comment by joncison** [comment]
cc @sduvaud
