### ISSUE TITLE
Adjust descriptions to fit in 500 char limit

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#278]
as defined in biotools_dev.xsd (https://github.com/bio-tools/biotoolsSchema/issues/84)

**Comment by hansioan** [comment]
@joncison For most of the descriptions this is fine, in the description consolidation part of the student work, they did just that. So most descriptions will fit in the 500 chars limit. Will need to see how the new ones look.

**Comment by joncison** [comment]
In biotoolsSchema 3.0.0 the limit is 1000 char,  In practice there are only 19 tools with length > 500.  Closing this.
