### ISSUE TITLE
Field in DB that toolID is "verified" 

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#279]
This is definitely required, and should be set to "true" for all things from the spreadsheet from hell, false by default.  What's the status of this @hansioan - I imagine something is already there?

**Comment by hansioan** [comment]
@joncison We have the field, will update it to mark the spreadsheet from hell tools as verified

**Comment by joncison** [comment]
very good, once done pls. close this

**Comment by hansioan** [comment]
re-open and update the field with the verified tools from the spreadsheet from hell

**Comment by joncison** [comment]
Field in DB is added, IDs that were verified in spreadsheet from hell have been set to "true" (1), and we have a new list of IDs to verify since that check (https://github.com/bio-tools/biotoolsRegistry/issues/357)
