### ISSUE TITLE
Last reviewed / updated field with sorting

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#28]
Suggested by reviewer !

**Comment by joncison** [comment]
"Last udpated" is done, "Last reviewed" should be done (once we have implemented the review process that will allow dropping of the "Unverified")

**Comment by hansioan** [comment]
This would involve adding some extra metadata (date and time) which would record whenever an owner or a curator would update information on the resource, or in some way mark it as reviewed.
