### ISSUE TITLE
5. Tweak the "Total annotations" graph

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#280]
The "Total annotations" graph in https://bio.tools/stats is made not very useful by inclusion of "Total" as a data series - this would be better given in it's own graph, _i.e._ two graphs:
1. showing the total # of annotations
2. showing the annotation breakdown

**Comment by baileqi** [comment]
The graphs should be separate now. Also, the graph width has been expanded to make reading the data easier.

**Comment by joncison** [comment]
fixed in https://dev.bio.tools
