### ISSUE TITLE
Invalid publication IDs

### ISSUE THREAD

**Issue by jaanisoe** [bio-tools/biotoolsRegistry#281]
While working on improving fetching of publication content for edamMap, I've found some publication IDs in bio.tools that are wrong. I guess fixing them is work-in-progress, however I'm listing them here, as there might be some non-obvious cases.

---

Uppercase "DOI:" as prefix. [It should be lowercase](https://www.doi.org/doi_handbook/2_Numbering.html#2.6.1).

DOI:10.1111/j.1755-0998.2010.02847.x
DOI:10.1186/gb-2006-7-7-r58
DOI:10.1111/mec.12354
DOI:10.1534/genetics.104.031799
DOI:10.1093/molbev/msu211
DOI:10.1086/302698
DOI:10.1007/978-1-4939-3578-9_13
DOI:10.1093/bioinformatics/btt187
DOI:10.1101/gr.201574.115
DOI:10.1093/bioinformatics/bth457
DOI:10.1105/tpc.112.108068
DOI:10.1126/science.1243518
DOI:10.14806/ej.17.1.200
DOI:10.1093/nar/gkw798
DOI:10.1186/gb-2008-9-10-r151
DOI:10.1101/gr.094052.109
DOI:10.1093/bioinformatics/bth092
DOI:10.1093/molbev/msp259

[Example from API](https://bio.tools/api/tool?format=json&page=1&name=Stacks)
and [in bio.tools](https://bio.tools/?page=1&name=%27Stacks%27) (check Publications in Detailed Display, where link is missing).

Also, somewhat related issue: https://github.com/bio-tools/biotoolsregistry/issues/229

---

A publication PMID is wrongly in the PMCID field. Entries in the PMCID field should have a "PMC" prefix.

24564762
26805938
24166654
20939868
26427375
25521701
23613489
25913176
26427375
24088582
26566788
24036418
27797758
27869826
28584021

Interestingly, if this is the case, bio.tools interprets this PMID in the PMCID field correctly as a PMID. But this causes problems in a few cases.

First, in a few cases, the same PMID is both in the PMID and PMCID fields.

[Example from API](https://bio.tools/api/tool?format=json&page=1&name=COCIN)
So [in bio.tools](https://bio.tools/?page=1&name='COCIN') we can see twice the same link.

Secondly, the ID in the PMCID field is actually a PMCID that is just wrongly missing the "PMC" prefix. This happens in two cases:
5210662
4299606

[Example from API](https://bio.tools/api/tool?format=json&page=1&name=SIAMCAT)
and [in bio.tools](https://bio.tools/?page=1&name='SIAMCAT') the PMCID gets interpreted as a PMID.
So we get a link to [this article](https://www.ncbi.nlm.nih.gov/pubmed/4299606), which is clearly wrong.

---

Extra space in front of ID:

" 10.1093/nar/gkw199"
" 10.1186/1471-2164-16-S6-S2"
" 10.1093/nar/gkv1209"
" 10.1371/journal.pone.0030126"
" 10.1186/gb-2010-11-2-r19"

[Example from API](https://bio.tools/api/tool?format=json&page=1&name=gOrth)
[In bio.tools](https://bio.tools/?page=1&name='gOrth')

---

Invalid DOI format:

/10.1371/journal.pone.0011988
/10.4137/cin.s13075
doi10.1007/978-1-62703-646-7_8
0.1101/115329
org/10.1093/nar/gks437

---

There is an interesting case with the invisible [zero-width space](https://en.wikipedia.org/wiki/Zero-width_space) Unicode character embedded in the DOI:

10.​1104/​pp.​104.​054700
(copy-paste it to the URL bar prepending https://doi.org/)

In `less` it shows up as 10.<U+200B>1104/<U+200B>pp.<U+200B>104.<U+200B>054700

[From API](https://bio.tools/api/tool?format=json&page=1&name=SPPG)
[In bio.tools](https://bio.tools/?page=1&name='SPPG')

---

Then, there are IDs which are syntactically correct, but which don't resolve to any publications. Finding these IDs would require actual querying of PubMed/EuropePMC with PMID/PMCID or resolving the DOI.

Non-complete list of such invalid DOIs currently in bio.tools:

doi:10.1093/ nar/gks1219
10.1186/s13742-015-0105-2, 2016.
10.1093/bioinformatics/btr304.
10.1016/j.compbiomed.2014.10.002.
10.1093/bioinformatics/btv189.
10.1002/humu.22503.
10.1093/bioinformatics/btv709.
10.1186/1471-2164-9-75.
10.1016/j.str.2008.10.017.
10.1038/nmeth.2242.
10.1111/j.1749-6632.2008.03756.x.
10.1074/mcp.M900317-MCP200.
10.1021/pr100118f.
10.1136/gutjnl-2011-301104.
10.1186/gb-2009-10-3-r25.
10.1093/bioinformatics/btp352.

Also, there are two invalid such PMIDs:

[19504496](https://www.ncbi.nlm.nih.gov/pubmed/?term=19504496)
[3579](https://www.ncbi.nlm.nih.gov/pubmed/?term=3579)

---

Of course, the most annoying wrong ID would be one that actually resolves to a publication, but which would be the wrong publication for the given bio.tools entry.

**Comment by joncison** [comment]
@hansioan : please fix this ASAP or reassign to one of your guys.  This has to be all fixed for M1.3 report (around litererature integration - due by early Dec).

@ekry - we'll be checking details regex's on Friday for doi, pmid & pmcid (along with everything else) - from the above, there seems to be an issue.

**Comment by jaanisoe** [comment]
A few more wrong DOIs:

[10.1016/s0168-9525(00)02024-4](https://doi.org/10.1016/s0168-9525(00)02024-4)
maybe correct: [10.1016/s0168-9525(00)02024-2](https://doi.org/10.1016/s0168-9525(00)02024-2)

[10.1016/s0168-9525(00)02024-3](https://doi.org/10.1016/s0168-9525(00)02024-3)
maybe correct: [10.1016/s0168-9525(00)02024-2](https://doi.org/10.1016/s0168-9525(00)02024-2)

[10.1101/009333](https://doi.org/10.1101/009333)
maybe correct: [10.1101/009332](https://doi.org/10.1101/009332)

The DOIs are syntactically correct, just resolving them gives a "Not Found" error. Maybe some of them might have been valid at the time of insertion, but gone missing afterwards.

Even more such DOIs (the second URL in each case is the potentially correct DOI, but this should be checked):

[10.1371/journal.pone.004311](https://doi.org/10.1371/journal.pone.004311)
[10.1371/journal.pone.0043117](https://doi.org/10.1371/journal.pone.0043117)

[10.1101/gr.160374](https://doi.org/10.1101/gr.160374)
[10.1101/gr.160374.113](https://doi.org/10.1101/gr.160374.113)

[10.1038/srep34516.](https://doi.org/10.1038/srep34516.)
[10.1038/srep34516](https://doi.org/10.1038/srep34516)

[10.1016/B978-0-12-385118-5.00029-3e](https://doi.org/10.1016/B978-0-12-385118-5.00029-3e)
[10.1016/B978-0-12-385118-5.00029-3](https://doi.org/10.1016/B978-0-12-385118-5.00029-3)

[10.1158/1538-7445](https://doi.org/10.1158/1538-7445)
[10.1158/1538-7445.COMPSYSBIO-B1-05](https://doi.org/10.1158/1538-7445.COMPSYSBIO-B1-05)
[10.1158/1538-7445.TRANSCAGEN-A2-45](https://doi.org/10.1158/1538-7445.TRANSCAGEN-A2-45)

[10.1093/nar/gks666None](https://doi.org/10.1093/nar/gks666None)
[10.1093/nar/gks666](https://doi.org/10.1093/nar/gks666)

[10.1093/gbe/evw010None](https://doi.org/10.1093/gbe/evw010None)
[10.1093/gbe/evw010](https://doi.org/10.1093/gbe/evw010)

[10.1093/nar/gkt530one](https://doi.org/10.1093/nar/gkt530one)
[10.1093/nar/gkt530](https://doi.org/10.1093/nar/gkt530)

[10.1021/pr4008078.](https://doi.org/10.1021/pr4008078.)
[10.1021/pr4008078](https://doi.org/10.1021/pr4008078)

[10.1136/gutjnl-2011-301104.](https://doi.org/10.1136/gutjnl-2011-301104.)
[10.1136/gutjnl-2011-301104](https://doi.org/10.1136/gutjnl-2011-301104)

[10.1093/nar/gkn000](https://doi.org/10.1093/nar/gkn000)
[10.1093/nar/gku1187](https://doi.org/10.1093/nar/gku1187)

[10.1186/1472-6807-10-23.](https://doi.org/10.1186/1472-6807-10-23.)
[10.1186/1472-6807-10-23](https://doi.org/10.1186/1472-6807-10-23)

[10.1021/pr400294c.](https://doi.org/10.1021/pr400294c.)
[10.1021/pr400294c](https://doi.org/10.1021/pr400294c)

[10.1038/gene.2010.3.](https://doi.org/10.1038/gene.2010.3.)
[10.1038/gene.2010.3](https://doi.org/10.1038/gene.2010.3)

[10.1039/c2mb05502c.](https://doi.org/10.1039/c2mb05502c.)
[10.1039/c2mb05502c](https://doi.org/10.1039/c2mb05502c)

[10.1186/1471-2105-12-115.](https://doi.org/10.1186/1471-2105-12-115.)
[10.1186/1471-2105-12-115](https://doi.org/10.1186/1471-2105-12-115)

[10.1111/j.1469-7580.2010.01290.x.](https://doi.org/10.1111/j.1469-7580.2010.01290.x.)
[10.1111/j.1469-7580.2010.01290.x](https://doi.org/10.1111/j.1469-7580.2010.01290.x)

Also, two additional PMIDs seem to be wrong (are not found in PubMed):

[28104628](https://www.ncbi.nlm.nih.gov/pubmed/?term=28104628)
maybe correct: [28453683](https://www.ncbi.nlm.nih.gov/pubmed/?term=28453683)

[25504941](https://www.ncbi.nlm.nih.gov/pubmed/?term=25504941)
maybe correct: [25828799](https://www.ncbi.nlm.nih.gov/pubmed/?term=25828799) or [28150248](https://www.ncbi.nlm.nih.gov/pubmed/?term=28150248)

**Comment by joncison** [comment]
any idea @hansioan what's gone wrong here?  it just needs a manual fix (and please close this issues once that's done) but I flag it up in cases there's a bug lurking here ...

**Comment by joncison** [comment]
@jaanisoe 

In the next release (soon!) DOIs with a prefix will not be allowed
@hansioan will fix the reported issues (above) and I will implement a future check via biotoolLint (https://github.com/bio-tools/biotoolsLint/issues/5)

**Comment by jaanisoe** [comment]
I see that the unresolvable DOIs issue will be fixed as part of biotoolsLint, cool! I re-checked for invalid publication IDs a few weeks ago and this DOI issue is by far the most common. There were also some new issues of a different kind, however these occurred very rarely. I'm listing them below.

---

As reported above, sometimes there is an ID in the PMCID field that is missing the "PMC" prefix.

For two tools, the publication PMID is set as the value of the PMID field (correct) and equally also as the value of the PMCID field (incorrect):
https://bio.tools/GEM_Mapper
https://bio.tools/MACARON

For two other tools, the publication PMID is incorrectly set as the PMCID value only:
https://bio.tools/parallelnewhybrid
https://bio.tools/angsd-wrapper

For two tools, the PMCID number part is correct, just the "PMC" prefix is missing (however, in that case the PMCID resolver can still work out the correct article in PMC):
https://bio.tools/GWAMA
https://bio.tools/PIQMIe

These few rare errors could be avoided, if the "PMC" prefix was a mandatory part of the PMCID.

---

In a few rare cases a specified PMID is missing in PubMed. This doesn't seem to be a mistake made when adding an entry to bio.tools, rather the PMID was removed in PubMed itself at a later date.

This tool has the PMID "19504496", which results in a "not available" error in PubMed:
https://bio.tools/sumosp

The PMIDs "24166654", "27116744" and "25504941" will result in a "was deleted because it is a duplicate of PMID" error in the following tools:
https://bio.tools/BoolSpace
https://bio.tools/gecko-csb
https://bio.tools/ProSight_Lite

But in the last cases, the PMID resolver is able to redirect to the correct PMID (that the deleted PMID was a duplicate of). However, not all metadata sources might not be able to do this and return no results when queried with the deleted PMIDs (like https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?retmode=xml&db=pubmed&id=24166654). So it would be better to replace the deleted duplicate PMIDs with the original ones.

---

Some misc. problems.

The value of PMCID is "None":
https://bio.tools/EOSC_pipeline-Reproducibility

The value of DOI is "none":
https://bio.tools/FuncExplorer

The DOI of the tool https://bio.tools/cisTEM should be "10.7554/eLife.35383" instead of "10.7554/eLife.35383.001" as the ".001" version points to the abstract whereas the first version points to the entire article. Publication metadata sources might like the version pointing to the entire article better.

---

In some cases, the ID could be valid and point to an existing article, with the only problem that it is the wrong article for the given tool. One interesting heuristic to find a few such mismatches is to look at PMIDs with a low value. These low-numbered PMIDs are identifying relatively old articles which in many cases have no place in bio.tools. I guess sometimes these PMIDs could be truncated versions of the correct PMID.

Starting from the lowest PMIDs:
* https://bio.tools/psychoprot has a publication with PMID "1", which is clearly the wrong article for the tool
* https://bio.tools/sr-tesseler has PMID "3579"
* https://bio.tools/Garlic has PMID "102733"
* https://bio.tools/augustus has an article with PMID "182186"
* https://bio.tools/Protein_Sequence_Logos has PMID "475985"
* but https://bio.tools/ndb has PMID "1384741", which is correct
* but for example PMID "1608201" of https://bio.tools/biomaRt is again not correct
* etc

**Comment by joncison** [comment]
Thanks a million @jaanisoe 

PMCIDs missing the "PMC" prefix, or with value of "None", are syntactically invalid and should have never occurred.  There seems to be a grot legacy which we need to deal with systematically.  Once we move the changes in dev.bio.tools into production, we'll be able to export the whole contents in XML format, allowing comprehensive syntax validation against biotoolsSchema 3.0.0, which will identify this (and all similar) issues.  In the meantime @hansioan , can you do a fix, also of the other misc issues raised?

I'll look at trapping what I can in biotoolsLint.

**Comment by joncison** [comment]
update to regex needed in biotoolsSchema, see https://github.com/bio-tools/biotoolsSchema/issues/123

**Comment by hansioan** [comment]
We are almost done with this, since we don't have any invalid tools anymore, we just need to check a few more publication ids (e.g. pmid or pmc or doi is too short, even though still valid)

**Comment by joncison** [comment]
@jaanisoe in summary
- _"DOI:" prefix (upper or lowercase)_ 
  - DOI prefix no longer valid
- _PMID is wrongly in the PMCID field. Entries in the PMCID field should have a "PMC" prefix_ 
  - @hansioan pls. confirm "PMC" prefix is now mandated
- Extra space in front of ID:  
  - [ ] @hansioan pls. confirm that these are fixed / prevented by _bio.tools, 
  - NB: tweak to biotoolsSchema is needed (https://github.com/bio-tools/biotoolsSchema/issues/134)
- Invalid DOI format: 
  - [ ] @hansioan pls. confirm that these are fixed / prevented by bio.tools
- _zero_ width space
  - don't see the problem, assume this was fixed
- _syntactically correct DOI, but which don't resolve to any publications._
  - will be caught by biotoolsLint (https://github.com/bio-tools/biotoolsLint/issues/5)
- _specific fixes from "jaanisoe commented on 23 Feb" (above)_
  - [ ] @hansioan confirm these are fixed
- issues from "jaanisoe commented on 5 Oct" (above)_
  - will be caught by biotoolsLint ()
- _value of PMCID / DOI is "None" or "none"
  - [ ] @hansioan confirm you checked / fixed in a case-INsensitive way
- _The DOI of the tool https://bio.tools/cisTEM should be "10.7554/eLife.35383" instead of "10.7554/eLife.35383.001" _
  - [ ] @hansioan to confirm this fixed
- _the ID could be valid and point to an existing article, with the only problem that it is the wrong article for the given tool._
  - not much we can about this
- _examples following "Starting from the lowest PMIDs:" (above)_
  - [ ] @hansioan to confirm these fixed

**Comment by joncison** [comment]
@hansioan  - please check list above; once each box is ticked we can close this thread.

**Comment by joncison** [comment]
all now checked ... will close in due course.

**Comment by joncison** [comment]
thanks @jaanisoe - your inputs here were super-useful
