### ISSUE TITLE
galaxy pasteur tool name 

### ISSUE THREAD

**Issue by hansioan** [bio-tools/biotoolsRegistry#282]
Names of galaxy pasteur tools end in `-IP`, I think we should changed that to be `(IP)`
example: `trimmomatic-IP` becomes `trimmomatic (IP)`

@joncison you agree?

**Comment by joncison** [comment]
According to naming patterns (http://biotools.readthedocs.io/en/latest/curators_guide.html#id18) that's right **but** if I recall right, I didn't bother renaming (in the spreadsheet from hell) tools whose descriptions are generated automatically, such as for Galaxy Pasteur.  Probably better to update regate (the tooling used for this), cc @hmenager to advise!

**Comment by hansioan** [comment]
@joncison to take this as a final stage of refactoring for "canonical" entries.

**Comment by joncison** [comment]
As discussed with @hmenager and @hansioan, I will go through these "*-IP" entries systematically, identifying ...

... entries where an independent tool exists, should be refactored into "canonical" entries (*i.e.* ):
1. retain existing homepage as ``<link><url>...</url><type>Service</type></link>``
2. change homepage to tool homepage (not Galaxy)
3. change both name *and* ID, *e.g.* "breseq-IP" -> "breseq"

entries for which an independent tool does not exist, leave them as-is

**Comment by joncison** [comment]
@hmenager @hansioan can we take a quick skype this morning to discuss briefly ... Hans and I need to understand, of the tools imported from Galaxy pasteur (where the descriptions are awesome, by the way!), what tools exist only in that instance (and so can keep their name/IDs) and what tools exist independently (where we'd need to merge into / create the "canonical" entries with appropriate names and IDs)

**Comment by joncison** [comment]
update from call with @hmenager & @hansioan we now have:
https://docs.google.com/spreadsheets/d/13sJxbfzG1rbfoqiKo_ilB4ZEKd0EmhDUoz55iYFDpHM/edit#gid=0
Actions:

[ ] - Herve to complete spreadsheet and hand over to Hans & I
* rename tools & IDs dropping the "-IP" suffix
* preserve existing homepage as link
* hotfix ``link->type`` enum extension for "Galaxy service" (see https://github.com/bio-tools/biotoolsSchema/issues/129) (using this for links)
* assign tools in suites (or "functional units" in packages) to a ``collection`` annotation (to be later refactored using formalised relationships)
* ensure

**Comment by joncison** [comment]
all now done @hmenager

**Comment by joncison** [comment]
done
