### ISSUE TITLE
Flicker of death

### ISSUE THREAD

**Issue by hansioan** [bio-tools/biotoolsregistry#287]
@ekry 
In some cases a search returns N results (shown in the number in the searchbox), but the actual results do not sum up to N and more pages are required, but not shown. And when trying to manually change the page from the URL there is a flicker.

An example of this is if one searches for "Conversion" function (i.e. Function=Conversion), the total number of results is 23, but there is only one page with less than 23 results.

https://bio.tools/?page=1&function=%27Conversion%27&sort=score

There is no way to go to page 2 unless page 2 is changed from the url:
https://bio.tools/?page=2&function=%27Conversion%27&sort=score

but then on this page we do get the tools, but with this flicker.

**Comment by baileqi** [comment]
It should be fixed now.

**Comment by joncison** [comment]
Fantastic !  I confirm this appears to fix the problem.  

@hmenager : pls. confirm that your search for "IFB", or credit == "ifb elixir-fr" work OK

**Comment by hmenager** [comment]
Yep, link works, no FOD. thank you @baileqi @ekry @hansioan and @joncison !
