### ISSUE TITLE
Replace obsolete CBS credits

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#288]
i.e. replace "Kristoffer Rapacki" with helpdesk / details from http://www.bioinformatics.dtu.dk/english/Service/Contact 

but be careful: KR may be credited for other tools (erroneously) : a legacy from very early days.  So in non-CBS cases, just delete the credit.

**Comment by joncison** [comment]
bumping the priority - this is the sort of thing we'll get pulled up on.  @hansioan please reassign this task to one of your guys to do ASAP

**Comment by hansioan** [comment]
@joncison already did, work in progress, will be done next week

**Comment by joncison** [comment]
cool, but they (everyone) should use GitHub more

**Comment by hansioan** [comment]
I have just assigned it today, @MigleSur is working on it.
