### ISSUE TITLE
Taverna duplicate

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#289]
https://bio.tools/taverna
https://bio.tools/apache_taverna

simply "Taverna" is the canonical name / ID

**Comment by joncison** [comment]
hold on ... these are different things ... closing this.

**Comment by redmitry** [comment]
Hello,

This could refer to different versions.
Current Apache incubating (v3) and old stable 2.5.

D.

**Comment by joncison** [comment]
thanks!  So I think keeping as distinct entries is right ...
