### ISSUE TITLE
Unlicensed potential issue?

### ISSUE THREAD

**Issue by hansioan** [bio-tools/biotoolsregistry#291]
@joncison 
If a tool is unlicensed, should it have a license annotation of  `Unlicensed` or `Unlicense`?
Because the option currently in bio.tools is `Unlicense` (without the `d`).

If this is wrong, we need to fix this in the license dropdown @ekry @baileqi

**Comment by hansioan** [comment]
or perhaps `Unlicense` refers to an actual license. 
If it does not, then we need to fix it and also move it at the bottom, where the value `Other` is, so that it is easily seen.

**Comment by hansioan** [comment]
@joncison @ekry @baileqi `Unlicense` is in fact a license, so ignore the above.
@joncison will the value for unlicensed software in the new schema be `Unlicensed` or `Not licensed` or what?

**Comment by joncison** [comment]
"Unlicensed" is supported in biotoolsSchema 3.0.0 

"Unlicense" too ... :) (see https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwi5sPCv297XAhUCIcAKHeB0A5IQFggoMAA&url=http%3A%2F%2Funlicense.org%2F&usg=AOvVaw3dNKZrlsAgP29kvXC1QWFZ) but they mean different things of course.

The distinction can be made clear in bio.tools once tips are exposed on enums (https://github.com/bio-tools/biotoolsregistry/issues/117)
