### ISSUE TITLE
Bad ID for gProfileR

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#297]
See:
![capture](https://user-images.githubusercontent.com/1506863/33583151-ca86a83e-d950-11e7-8422-127239b7cb85.PNG)

It needs something sensible, and distinct from https://bio.tools/gprofiler (which has almost identical name)

cc @veitveit the ID will have to be updated (once fixed) in SupplTable1.csv for our paper

**Comment by hansioan** [comment]
@joncison @veitveit 
When this was registered there was an ID conflict and that's why the number got appended at the end. 
Suggestion of ID: `gprofile_r`, `gprofiler_rpackage`, `gprofiler_package`

**Comment by joncison** [comment]
``gprofile_r``

The IDs with numbers have to be fixed (https://github.com/bio-tools/biotoolsRegistry/issues/299) and the system refacatored to prevent this happening in future (https://github.com/bio-tools/biotoolsRegistry/issues/300)
