### ISSUE TITLE
4. Registration interface erroneously says "Add function"

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#298]
![capture](https://user-images.githubusercontent.com/1506863/33585133-9fe8da02-d95a-11e7-9fe7-d75191dc5d4d.PNG)

it should be "Add operation" - which adds to the confusion/lack of usability

**Comment by baileqi** [comment]
Should be fixed now.

**Comment by joncison** [comment]
Looking at https://dev.bio.tools, more needs to be done:
1. Textbox (at top) should have default value of "Operation" not "Function"
2. Button label (at bottom) should be "Add function" not "Add operation"

cc @hansioan : did I miss anything?

**Comment by hansioan** [comment]
@joncison yes and maybe one more
more exactly @baileqi 
Based on the screenshot:
![operation](https://user-images.githubusercontent.com/12627065/35508892-61425ad0-04f2-11e8-8b35-d3e81046548d.png)

the word `Function` should be replaced with `Operation`


Based on this screenshot:
![add_function](https://user-images.githubusercontent.com/12627065/35508937-98703e46-04f2-11e8-8afb-7784a69e4abd.png)

`Add operation` should say `Add function`
and
`Hide functions` should say `Hide function` and the hiding functionality should only hide a single function at a time (and the `Hide function` should be present after each function block). I don't see any point in hiding all functions if there are only functions in this tab...
