### ISSUE TITLE
Systematic check & fix broken (numeric-appended) toolIDs

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#299]
see e.g. https://github.com/bio-tools/biotoolsRegistry/issues/297

they need to be identified and replaced with human-readable IDs.

**Comment by hansioan** [comment]
@joncison 
This fix will have to happen after we move to schema 3 and new logic because then we won't have the issue in the future.

**Comment by hansioan** [comment]
There are still dodgy IDs , but it's best we clean them after the migration, when we don't allow these dodgy IDs to appear anymore, if we clean them now we might still have dodgy IDs by the time we migrate.

**Comment by joncison** [comment]
full list of IDs
https://docs.google.com/spreadsheets/d/1MrU10RnIlMLiqWXUuvwWuPvUAeDtxXdGBGxfpOUaYf4/edit#gid=0

**Comment by joncison** [comment]
done
