### ISSUE TITLE
Tool suggestion/recommendation system

### ISSUE THREAD

**Issue by Ahto123** [bio-tools/biotoolsRegistry#302]
Recently, there has been a need for some system that allows people (who may not be users) to suggest tools to bio.tools. The thing is that these people don’t want to add those tools by themselves (because they don’t have the time) but still want bio.tools to have it in its registry. So, is it possible to make that kind of suggestion/recommendation system? Ideally, it would be necessary to input just the name of the tool but because it may not be specific enough then maybe adding homepage or article PMID should be compulsory? Adding more requirements wouldn’t probably be a good idea since it may decrease people’s willingness to use it.

**Comment by joncison** [comment]
agree this would be nice, one option is a little "Suggestions" button that prompts for:
* tool name (mandatory)
* homepageURL (mandatory)
* publication ID (optional)
* description (optional)

and put this button in the bio.tools menu

**Comment by hansioan** [comment]
@Ahto123 
This will be solved in schema 3.0.0 where we only demand tool name, homepage and description in order to register a tool. Hopefully this is not too much to ask.

**Comment by joncison** [comment]
cc @Ahto123
