### ISSUE TITLE
7. Sorting data format field 

### ISSUE THREAD

**Issue by OlivierCollin** [bio-tools/biotoolsRegistry#303]
During the creation of a new record, when selecting the Data Format, the curator is facing a huge unsorted list of file formats. 
Is there a way to sort the file formats ?

**Comment by hansioan** [comment]
@ekry The tree component would need sorting on the elements.

@OlivierCollin you can use a working beta version of a new EDAM annotatio tool, the fields are sorted there, see demo at:
https://github.com/bio-tools/edamToolAnnotator

**Comment by joncison** [comment]
@hansioan - great to have some (even some super-basic) usage guideline, see https://github.com/bio-tools/edamToolAnnotator/issues/1

**Comment by joncison** [comment]
@OlivierCollin, @hansioan has made a fix - will appear in the next release (out soon)

**Comment by joncison** [comment]
cc @OlivierCollin
