### ISSUE TITLE
confirm deleting a subdomain entry

### ISSUE THREAD

**Issue by bagnacan** [bio-tools/biotoolsRegistry#308]
Dear all,
on my "manage-subdomains" section, I accidentally deleted an entry I had previously defined.
Sure this is my fault, but I would suggest to add a bubble appearing as a modal overlay, asking: "Are you sure you want to delete the subdomain XYZ?".
What do you think?
Thanks for your time and effort

**Comment by joncison** [comment]
hi @bagnacan 

sorry for long delay.  yeah, this is bad :)   @hansioan is working on a fix right now ...

**Comment by hansioan** [comment]
Added a confirmation message when clicking the delete button.

**Comment by joncison** [comment]
cc @bagnacan
