### ISSUE TITLE
Tools with "None" as description

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#309]
![capture](https://user-images.githubusercontent.com/1506863/34674909-977a7a5c-f47f-11e7-8468-bd7eacfaa8b9.PNG)
see e.g. https://bio.tools/lapmix

any idea @hansioan how this has happened ?

**Comment by joncison** [comment]
I'm adding the description now ...

**Comment by hansioan** [comment]
@joncison Sorry, error on my side, fixed!
