### ISSUE TITLE
main page displaying last viewed bio.tools subdomain header

### ISSUE THREAD

**Issue by bagnacan** [bio-tools/biotoolsRegistry#311]
Dear all,
after I visited the bio.tools subdomain "denbi-rbc" at http://denbi-rbc.bio.tools, I clicked on the Elixir logo on top left to return to the homepage (at https://bio.tools/search). Here however, although the URL and tools listed in the page change accordingly, I'm still able to visualize the heading explaining what "denbi-rbc" is.
The desired behaviour would be instead that of not visualizing the heading for "denbi-rbc" once I leave that page. I tried also with another subdomain, and obtained the same behaviour.
You can replicate the issue by:
- visiting the [denbi-rbc subdomain page](http://denbi-rbc.bio.tools), and then
- clicking on the elixir logo on the top left. You'll notice that the header is still there

Thanks
Andrea

**Comment by hansioan** [comment]
@bagnacan 
This is a known issue we have with subdomains
@ekry and @baileqi are working on a fix.

**Comment by joncison** [comment]
@bagnacan - @baileqi will have this fixed soon, I hope middle of this week

**Comment by bagnacan** [comment]
Thank you all

**Comment by joncison** [comment]
@bagnacan this now fixed
