### ISSUE TITLE
Subdomains do not support "-" character

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#312]
Multiple issues around this, as discussed last year in detail

support for "-" is needed so we can have _e.g._

- denbi.bio.tools
- denbi-node1.bio.tools
- denbi-node2.bio.tools

@baileqi I understand you've been assigned this task; please ensure to discuss it with @hansioan or @ekry as necessary, so we can get a fix ASAP (we need a fix before taking a skype with the de.NBI guys, already overdue.  See https://github.com/bio-tools/biotoolsRegistry/issues/311. ) 

thanks!

**Comment by joncison** [comment]
confirmed by @hansioan : '-' are now supported in subdomain names

we need conventions on how you can eumulate a subdomain hierarchy using dashes

**Comment by hmenager** [comment]
fix confirmed: https://rare-diseases.dev.bio.tools/
