### ISSUE TITLE
spaces in "version" property

### ISSUE THREAD

**Issue by redmitry** [bio-tools/biotoolsRegistry#314]
Hello,
According the Biotools 2.0 Schema, there couldn't be spaces.
On the other hand, there are some tools those version is not properly formatted.

for instance:

massxpert - "massXpert 2"
bambus: - "Bambus 2"
taxonomy_summary-ip - "0.1 beta"
selecthitscore-ip - "0.1 beta"
selectbesthit-ip - "0.1 beta"
sabund-ip - "0.1 beta"

Cheers,

D.

**Comment by joncison** [comment]
thanks for reporting, but we (== @piotrgithub1 and @ekry) are in the middle of migrating everything to biotoolsSchema 3.0.0 (where spaces are allowed in version specifications) - aiming to complete by the end of this month.

**Comment by joncison** [comment]
this resolved in the release we're working on now (compliant to biotoolsSchema 3.0.0)

**Comment by hmenager** [comment]
if fix means it's ok to have versions with a space, then yes it's fixed.

**Comment by joncison** [comment]
yup that's right @hmenager, thanks for checking
