### ISSUE TITLE
Some tags on Tool Cards will be meaningless to many users

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#317]
Reported recently

Look at:
https://bio.tools/signalp

No one will know what "CBS" and "Other" mean.  It's easily solved if we add pop-ups with tips from biotoolsSchema (https://github.com/bio-tools/biotoolsRegistry/issues/70, see also https://github.com/bio-tools/biotoolsRegistry/issues/117)

cc @piotrgithub1 @baileqi

**Comment by joncison** [comment]
Tool tips added to all tags (using simplified text from biotoolsSchema

Tags for ELIXIR Node and Platforms have been made into links.

**Comment by hmenager** [comment]
fix confirmed
extremely nice improvement to the UI, congrats ;)
