### ISSUE TITLE
Adding collection names and editing rights

### ISSUE THREAD

**Issue by Ahto123** [bio-tools/biotoolsRegistry#319]
Sometimes it is relevant to add collection names to many tools (tens or even hundred). Is there or should there be a better way to do it than just requesting editing rights (getting those can take quite a while)? It would make curators work easier. Any thoughts?

**Comment by joncison** [comment]
Please speak directly to @hansioan about this - if you have tens or hundreds to add, then this should be done directly via SQL or some other mechanism.  I suspect we'd need a list of toolIDs with the replacement or additional element value(s).  @hansioan : please advise !

**Comment by joncison** [comment]
@Ahto123 

it could be, in future, that some fields are gloabally editable.  But for now just ask me or Hans if you have many such edits to make.
