### ISSUE TITLE
Labels should be more useful

### ISSUE THREAD

**Issue by Federico77z** [bio-tools/biotoolsRegistry#327]
In the "compact" display the topic labels should be links pointing to a new search within bio.tools for services covering the same topic. In the same way, I think that in the "detailed" view the linking of functions and topics to the corresponding EDAM entries are not that useful. The link should point to new bio.tools searches using the function/topic/output etc... If necessary the links to EDAM can be preserved maybe by putting a small icon near each term with the link to EDAM.

**Comment by joncison** [comment]
Absolutely.  This one is trivial to do, and has been raised many times in the past (e.g. https://github.com/bio-tools/biotoolsRegistry/issues/120 and https://github.com/bio-tools/biotoolsRegistry/issues/63).  cc @piotrgithub1

**Comment by joncison** [comment]
@Federico77z - this is now implemented in the "Detailed view" and (in next release) will appear in "Compact" view, too (@hansioan is doing it right now)

**Comment by hmenager** [comment]
fix confirmed

**Comment by joncison** [comment]
@Federico77z
