### ISSUE TITLE
Not clear how the scoring works

### ISSUE THREAD

**Issue by sduvaud** [bio-tools/biotoolsRegistry#328]
Tried the following URL:
https://bio.tools/?page=4&q=polymorphism%2Bvariant&sort=score

![screen shot 2018-02-23 at 18 04 54](https://user-images.githubusercontent.com/15673655/36606529-40f224be-18c4-11e8-88e8-6464ac721cf4.png)

==> 2/2 words are found in the SwissVar record with a total of 5 matches.
==> 1/2 words are found in the 2kplus2 record with a total of 1 matche.
but 2kplus2 shows up before SwissVar. Shouldn't it be the other way round?

**Comment by joncison** [comment]
It's prioritising full-token matches to EDAM terms, over matches in the descriptions, which is probably OK.  What we really need is a dedicated workshop to evaluate the search performance - that definitely should be done (ideally this year) but is out of scope of the revision required for the submission of the paper.

**Comment by hansioan** [comment]
To be more specific it scores topic matches higher than description matches.

**Comment by joncison** [comment]
@sduvaud we can't ever really make the scoring fully transparent (it's all encoded in the elastic parameterisation), the more important thing is that we do user testing / optimisation of it.

But if you think we should try to document the search behaviour, please request that at https://github.com/bio-tools/biotoolsdocs/issues

**Comment by joncison** [comment]
NB: see mooted hackathon (https://github.com/bio-tools/biotoolsRegistry/issues/361)
