### ISSUE TITLE
Detailed view - modifying columns w/o visual indication

### ISSUE THREAD

**Issue by krab1k** [bio-tools/biotoolsRegistry#329]
There should be some icon (like ⚙) which helps the user to see that columns are actually editable.

![image](https://user-images.githubusercontent.com/16164737/36724633-11228c04-1bb4-11e8-9dfd-e191d13a2c70.png)

**Comment by hansioan** [comment]
@krab1k There used to be an icon before, @baileqi can we add the 3 lines (hamburger menu) that we had before to show that this is editable?

**Comment by joncison** [comment]
@baileqi cc @piotrgithub1 this must be fixed for the report submission next month - will you please take a look, and get back here re what action was taken?

**Comment by hansioan** [comment]
Fixed.
