### ISSUE TITLE
Mismatch between IDs of a publication

### ISSUE THREAD

**Issue by jaanisoe** [bio-tools/biotoolsRegistry#332]
A single publication can have multiple IDs specified: PMID, PMCID and DOI. Sometimes, two such IDs of a single publication are actually identifying two distinct publications.

For example, the bio.tools entry "[zooma](https://bio.tools/zooma)" has a publication with "pmid" : "[21995944](https://www.ncbi.nlm.nih.gov/pubmed/?term=21995944)" and "doi" : "[10.1093/nar/gkv1352](https://doi.org/10.1093/nar/gkv1352)". The first ID refers to an article titled "Anatomy ontologies and potential users: bridging the gap." and the second ID refers to an article titled "The European Bioinformatics Institute in 2016: Data growth and integration". The corresponding DOI for the specified PMID 21995944 should actually be 10.1186/2041-1480-2-S4-S3.

Such a mismatch can be seen in a few additional cases:
"id" : "[biomodels](https://bio.tools/biomodels)" -- "pmid" : "[20587024](https://www.ncbi.nlm.nih.gov/pubmed/?term=20587024)" & "doi" : "[10.1093/nar/gkv1352](https://doi.org/10.1093/nar/gkv1352)"
"id" : "[chembl_api](https://bio.tools/chembl_api)" -- "pmid" : "[19194660](https://www.ncbi.nlm.nih.gov/pubmed/?term=19194660)" & "doi" : "[10.1093/nar/gkv1352](https://doi.org/10.1093/nar/gkv1352)"
"id" : "[dictybase_update_2011](https://bio.tools/dictybase_update_2011)" -- "pmid" : "[21087999](https://www.ncbi.nlm.nih.gov/pubmed/?term=21087999)" & "doi" : "[10.1007/978-1-62703-302-2_4](https://doi.org/10.1007/978-1-62703-302-2_4)"
"id" : "[tronco](https://bio.tools/tronco)" -- "pmid" : "[26861821](https://www.ncbi.nlm.nih.gov/pubmed/?term=26861821)" & "doi" : "[10.1093/bioinformatics/btv296](https://doi.org/10.1093/bioinformatics/btv296)"
"id" : "[predictionet](https://bio.tools/predictionet)" -- "pmid" : "[22096235](https://www.ncbi.nlm.nih.gov/pubmed/?term=22096235)" & "doi" : "[10.1038/nmeth.3252](https://doi.org/10.1038/nmeth.3252)"

**Comment by joncison** [comment]
That's not good ... but should be possible to automatically identify such cases and fix.  cc @hansioan FHI.

**Comment by hansioan** [comment]
The data has been fixed, but the verification functionality is not implemented in the codebase.

**Comment by joncison** [comment]
Verification to be taken forward via biotoolsLint

**Comment by joncison** [comment]
This issue was moved to bio-tools/biotoolsLint#2
