### ISSUE TITLE
Resetting password is not reflected in the API

### ISSUE THREAD

**Issue by FrodePedersen** [bio-tools/biotoolsRegistry#335]
Good evening.

Attempting to login through the API using the example of: http://biotools.readthedocs.io/en/latest/api_reference_dev.html#token

`curl -X POST -H "Content-Type: application/json" -d '{"username":"username","password":"password"}' "https://dev.bio.tools/api/rest-auth/login/"`

resulted in two different issues.

1) I created a new user on the bio.tools page but when attempting to log in using the API it returns: {"general_errors":["Unable to log in with provided credentials."]}. I checked multiple times that I was using the correct username and password, as they worked when attempting to log into the webpage itself. I tried using both the "username", "password" combination and the "email", "password".

2) My colleague tried to login using his older account, which worked and he received a key, but upon resetting the password (to check whether my issue might be because of an update latency on the server side), he discovered that the new password did no longer grant him access through the API verifying that it might indeed be a possibility. He was able to log onto bio.tools using the new password through the browser though. He then attempted to use his old password which then granted him access through the API but not through the browser.

it seems there might be a security concern here, making it possible to login using two different passwords of the same user.

-Frode P.

**Comment by joncison** [comment]
Sorry for the troubles Frode, @piotrgithub1 will you please help out here?

**Comment by joncison** [comment]
@FrodePedersen:  @hansioan and I just tested this quite thoroughly, and all appears now to be working OK.  Please re-open the issue if you still have a problem.
