### ISSUE TITLE
Erroneous DOIs ? 

### ISSUE THREAD

**Issue by albangaignard** [bio-tools/biotoolsRegistry#337]
From the RDF data dump script, I found 3 DOIs that cannot be used to build a URL : 
```
https://dx.doi.org/10.4172/ jpb.1000197 does not look like a valid URI, trying to serialize this will break.
https://dx.doi.org/10.1371/journal.pone.0079894. eCollection 2013 does not look like a valid URI, trying to serialize this will break.
https://dx.doi.org/10.1093/bioinformatics/btr306. Epub 2011 May 17 does not look like a valid URI, trying to serialize this will break.
```
It seems that 
 - a ` ` (space) should not be here : `...2/ jp...` for the first one, 
 - `. eCollection 2013` should be removed from the second one, 
 - `. Epub 2011 May 17` should be removed from the last one.

**Comment by hansioan** [comment]
Fixed, thanks @albangaignard for point the errors about.
@piotrgithub1 I think a validation should be in place where it doesn't allow spaces in DOIs

**Comment by albangaignard** [comment]
Hi again, for a long period, I had an issue with the nightly worker wich dumps the content of bio.tools into RDF. Its alive again :-), and I found another DOI issue : 
```
Exception: "https://doi.org/10.1038/s41588-018-0145-5 DO" does not look like a valid URI, I cannot serialize this as N3/Turtle. Perhaps you wanted to urlencode it? 
```

@hansioan, @joncison, maybe a quick fix for this entry would be enough for now ? 
Thanks again for the huge work on content curation !!

**Comment by joncison** [comment]
thanks for reporting @albangaignard 

@hansioan could you take a look please?  PS. I think before pushing all the latest changes from dev.bio.tools to production, we should dump out the whole contents and validate against biotoolsSchema 3.0.0 (the above DOI syntax is invalid, I think, and I'm not sure how this one has cropped up).

**Comment by joncison** [comment]
We'll revisit the DOI validation (which is tricky) to avoid errors in future (see https://github.com/bio-tools/biotoolsSchema/issues/134)

**Comment by joncison** [comment]
cc @albangaignard
