### ISSUE TITLE
Bug in the search: searching for a format

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsRegistry#343]
Example: BAM
There is at least one (or more) valid annotation: https://bio.tools/wavcluster
However, https://bio.tools/?output=BAM doesn't return any records.

In addition:
- This bug applies to input and outupt attributes, and maybe other attributes as well
- Clicking an a format in Bio.Tools (_e.g._ in https://bio.tools/wavcluster) seems to call a script instead of directly linking to the search URL (_e.g._ https://bio.tools/?output=BAM). Is that so?
- Clicking an a format in Bio.Tools (_e.g._ in https://bio.tools/wavcluster), should search for both records that have it as an output and ones that have it as an input (so a functionality of something like **https://bio.tools/?io=BAM**). This should also be enabled in the search bar, and would be really great and useful!

Many thanks for looking into this!

**Comment by hansioan** [comment]
Yeah, I can reproduce this. The weird thing is that:
https://bio.tools/?output=bam
works, so it looks like an upper/lower case issue. Will have to look more into this. 
cc @piotrgithub1 @baileqi

**Comment by joncison** [comment]
@matuskalas : @hansioan has fixed this in his version - to go into next release

**Comment by hmenager** [comment]
fix confirmed

**Comment by joncison** [comment]
cc @matuskalas
