### ISSUE TITLE
Add a tool to a collection without having to request edit rights

### ISSUE THREAD

**Issue by lmatalonga** [bio-tools/biotoolsRegistry#352]
From Leslie Matalonga (ELIXIR-ES, EXCELERATE WP8):

It is quite complicated to add tools in a collection as I have to request edit rights. First I have to wait until permission is accepted (which take time and I still have some tools pending to proceed) and also once I am given the permission I feel that I have “too much power” as I am able to edit the whole entry. Would it be possible in the future to create collections without having to request edit rights? I know that some other partners from EXCELERATE wanted to use your registry to create different collections and this might also be useful for them.

Thanks!
Leslie
Contact email: leslie.matalonga@cnag.crg.eu

**Comment by joncison** [comment]
This is related to https://github.com/bio-tools/biotoolsRegistry/issues/319

Basically @lmatalonga if you have lots of collection annotations to make, compile a list and send these to @hansioan (he will do the update for you).  Alternatively, create a subdomain for your tools.

In future, we can think about editing collections without having edit rights, which would be an aspect of "drive-by" curation (https://github.com/bio-tools/biotoolsRegistry/issues/57).

Closing this for now (reopen as necessary)
