### ISSUE TITLE
PROBLEM with Developed_RD-Connect domain

### ISSUE THREAD

**Issue by lmatalonga** [bio-tools/biotoolsRegistry#364]
Dear @piotrgithub1  @hansioan @joncison,

We are using domains to retrieve information from tools developed within the RD-Connect project in the website through your API. The domain "developed_RD-Connect" › should have 12 tools, which are the ones I entered (screenshot attached) but if we query this domain we retrieve 42 tools which are the ones corresponding to the RD-Connect domain. 
Can you please check what is happening and if it is related to #362 

Thanks, 

Leslie

![image](https://user-images.githubusercontent.com/25792446/46790139-805c5000-cd3e-11e8-8e1c-eb5f824704ed.png)

**Comment by hansioan** [comment]
@lmatalonga 
Working on a fix right now, will update this thread soon

**Comment by hansioan** [comment]
@lmatalonga 
Should be fixed now, please check and confirm, so I can close the issue.

**Comment by hansioan** [comment]
@lmatalonga 
Also clear cache just to make sure it's not from that.

**Comment by lmatalonga** [comment]
Fixed! Thanks!
