### ISSUE TITLE
wrong publication

### ISSUE THREAD

**Issue by nomenia** [bio-tools/biotoolsRegistry#367]
Wrong publication is cited on the PQSfinder page at https://bio.tools/pqsfinder
The correct publication should be https://academic.oup.com/bioinformatics/article-abstract/33/21/3373/3923794

**Comment by joncison** [comment]
thanks, will be fixed soon

PS.  you can also "Request edit rights" on the entry and fix this yourself, should you wish to

**Comment by joncison** [comment]
cc @nomenia
