### ISSUE TITLE
Sort out mailing lists wrt new governance

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#368]
Clean-up registry, registry-core and registry-announce mailing lists given what's said / new group structures in https://github.com/bio-tools/biotoolsRegistry/blob/master/contribution.md

**Comment by joncison** [comment]
hey @piotrgithub1 ... could you please create registry-dev on http://elixirmail.cbs.dtu.dk/mailman/admindb/ ?

I'd do it myself but don't have privileges.

All do all the config, migrating user emails etc. once you create the list. 

thanks!

PS: it's needed so we can get all the docs straight in time for the paper

**Comment by piotrgithub1** [comment]
Yeah, will do tomorrow morning. It's a pain in the neck old school system that I'm kinda afraid to look at too intensely or it will crumble into dust...

**Comment by joncison** [comment]
thanks for helping with this @piotrgithub1  - if a new mail system appears than pls ping me here.
