### ISSUE TITLE
rare disease edam ontology inconsistencies 

### ISSUE THREAD

**Issue by JenHarrow** [bio-tools/biotoolsRegistry#371]
@hansioan @joncison why do some of these resources not have "rare disease" edam ontology added to the  terms as the term is highlighted in the txt many times (looking at the current bio.tools )
<img width="983" alt="screen shot 2018-11-13 at 11 26 58" src="https://user-images.githubusercontent.com/38695753/48410894-da827380-e737-11e8-86bb-ec3ae2502d41.png">

**Comment by hansioan** [comment]
@JenHarrow It's usually due to how people annotate the tools and their knowledge of EDAM and software that browse EDAM. I've added Rare diseases topics to the tools in the screenshot.

**Comment by joncison** [comment]
@JenHarrow I took a second pass through and think everything that should have topic =="Rare diseases" does so (ping us here otherwise)

**Comment by joncison** [comment]
cc @JenHarrow
