### ISSUE TITLE
Add EDAM operations to the default list view of entries + LABEL COLOURS

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsRegistry#374]
- [x] In addition to Topics, OS, Entry type, it's crucial for tools and workflows to show what their function is.

Maybe a different colour of the label would be nice.

- [x] And also EDAM Topics and other kinds of labels should have the same colour throughout the webapp (now Topics are blue in the list and orange on the tool card)

To consider is using the standardised EDAM sub-ontology colours, or something inspired by them.

**Comment by hansioan** [comment]
Added consistent, EDAM-compliant colors for EDAM topics and operations.

**Comment by joncison** [comment]
cc @matuskalas
