### ISSUE TITLE
Rendering of "None" version ...

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#379]
*e.g.* https://dev.bio.tools/MetaPhlAn

prob. simplest to just remove all annotations of versions of "None" (which is just legacy cr*p) ?

**Comment by hansioan** [comment]
@joncison fixed this in dev, will need to fix it in production after moving to schema 3

https://dev.bio.tools/MetaPhlAn

**Comment by joncison** [comment]
nice job !
