### ISSUE TITLE
Non valid tools as of schema 3.0

### ISSUE THREAD

**Issue by hansioan** [bio-tools/biotoolsRegistry#386]
List of tools:
- [x] https://bio.tools/bipa
- [x] https://bio.tools/ecid
- [x] https://bio.tools/chooch
- [x] https://bio.tools/phyml-sms_oneclick-ip
- [x] https://bio.tools/phyml_oneclick-ip
- [x] https://bio.tools/gblocks_oneclick-ip
- [x] https://bio.tools/fa-extract-sequence-ip
- [x] https://bio.tools/gblocks-ip
- [x] https://bio.tools/converter_genbank_to_fasta-ip
- [x] https://bio.tools/fastme_oneclick-ip
- [x] https://bio.tools/fasta_to_phylip-ip
- [x] https://bio.tools/modencode_peakcalling_macs2-ip
- [x] https://bio.tools/muscle-ip
- [x] https://bio.tools/noisy_oneclick-ip
- [x] https://bio.tools/seqtypedetect-ip
- [x] https://bio.tools/dsap
- [x] https://bio.tools/grs
- [x] https://bio.tools/hawkeye
- [x] https://bio.tools/rna-mate
- [x] https://bio.tools/tileqc
- [x] https://bio.tools/virushunter
- [x] https://bio.tools/webprinses
- [x] https://bio.tools/ewce
- [x] https://bio.tools/gene.e
- [x] https://bio.tools/icr
- [x] https://bio.tools/img
- [x] https://bio.tools/scipion
- [x] https://bio.tools/InCroMAP
- [x] https://bio.tools/RDFScape
- [x] https://bio.tools/PATBox
- [x] https://bio.tools/MUPRED
- [x] https://bio.tools/SEAS
- [x] https://bio.tools/PathScore
- [x] https://bio.tools/OpenGrowth
- [x] https://bio.tools/ORION
- [x] https://bio.tools/GDT
- [x] https://bio.tools/PEASE
- [x] https://bio.tools/NRWRH
- [x] https://bio.tools/Suite16
- [x] https://bio.tools/Peditree
- [x] https://bio.tools/COSMOS
- [x] https://bio.tools/scowl
- [x] https://bio.tools/consensuspathdb
- [x] https://bio.tools/dima_domain_interaction_map
- [x] https://bio.tools/gassst
- [x] https://bio.tools/aphidbase
- [x] https://bio.tools/lepidodb
- [x] https://bio.tools/Peptidequant
- [x] https://bio.tools/SWITCHdna
- [x] https://bio.tools/bcov
- [x] https://bio.tools/MICC
- [x] https://bio.tools/virusmint
- [x] https://bio.tools/virusmentha
- [x] https://bio.tools/proabc
- [x] https://bio.tools/psi-mi_validator
- [x] https://bio.tools/pdbepisa
- [x] https://bio.tools/PedigreeQuery
- [x] https://bio.tools/radar
- [x] https://bio.tools/Oligonucleotide_Search
- [x] https://bio.tools/NBC
- [x] https://bio.tools/P-SAMS
- [x] https://bio.tools/fuzzyclust
- [x] https://bio.tools/intact
- [x] https://bio.tools/Oncotator
- [x] https://bio.tools/phdhtm
- [x] https://bio.tools/profhtm
- [x] https://bio.tools/Network_Archaeology
- [x] https://bio.tools/VIRALpro
- [x] https://bio.tools/gwaspi
- [x] https://bio.tools/sfinx
- [x] https://bio.tools/klifs
- [x] https://bio.tools/pdestrian
- [x] https://bio.tools/dbVAR
- [x] https://bio.tools/SeqMS
- [x] https://bio.tools/hypercldb
- [x] https://bio.tools/mapsplice
- [x] https://bio.tools/flash
- [x] https://bio.tools/dsrc
- [x] https://bio.tools/glycomod
- [x] https://bio.tools/pubmeth
- [x] https://bio.tools/iStable
- [x] https://bio.tools/genemania
- [x] https://bio.tools/psichomics
- [x] https://bio.tools/blast2go
- [x] https://bio.tools/Rnall
- [x] https://bio.tools/RBPmap
- [x] https://bio.tools/methmarker
- [x] https://bio.tools/GWAS_catalog
- [x] https://bio.tools/phyleasprog
- [x] https://bio.tools/chemprot
- [x] https://bio.tools/hexpochem
- [x] https://bio.tools/netgene2
- [x] https://bio.tools/ecr_browser
- [x] https://bio.tools/dire
- [x] https://bio.tools/dichromatch
- [x] https://bio.tools/gasv
- [x] https://bio.tools/DDI-CPI
- [x] https://bio.tools/gwas3d
- [x] https://bio.tools/cangs
- [x] https://bio.tools/TheSeqManipSuite2
- [x] https://bio.tools/IndividualizedPath
- [x] https://bio.tools/LocusExplorer
- [x] https://bio.tools/mint
- [x] https://bio.tools/mentha
- [x] https://bio.tools/Jannovar
- [x] https://bio.tools/GREGOR
- [x] https://bio.tools/Alphabet
- [x] https://bio.tools/nmsim
- [x] https://bio.tools/CracTools
- [x] https://bio.tools/Skylign
- [x] https://bio.tools/Arpeggio
- [x] https://bio.tools/FRED
- [x] https://bio.tools/GO2MSIG
- [x] https://bio.tools/CisMiner
- [x] https://bio.tools/WordClCytoscPlg
- [x] https://bio.tools/Boiler
- [x] https://bio.tools/RseqFlow
- [x] https://bio.tools/SeqTU
- [x] https://bio.tools/cisTEM
- [x] https://bio.tools/miFRame
- [x] https://bio.tools/TRDistiller
- [x] https://bio.tools/gprofiler
- [x] https://bio.tools/miRTar2GO
- [x] https://bio.tools/Crysalis
- [x] https://bio.tools/expVIP
- [x] https://bio.tools/SymbioGBR
- [x] https://bio.tools/DCell
- [x] https://bio.tools/hu.MAP
- [x] https://bio.tools/paa
- [x] https://bio.tools/pcddb
- [x] https://bio.tools/xplatcom
- [x] https://bio.tools/BayesTyper
- [x] https://bio.tools/NOREVA
- [x] https://bio.tools/CNVcaller
- [x] https://bio.tools/FusorSV
- [x] https://bio.tools/MACARON
- [x] https://bio.tools/mTCTScan
- [x] https://bio.tools/CELLmicrocosmos_4_PathwayIntegration_CmPI
- [x] https://bio.tools/cpPredictor
- [x] https://bio.tools/DominoEffect
- [x] https://bio.tools/TnT
- [x] https://bio.tools/multiqc
- [x] https://bio.tools/epicontacts
- [x] https://bio.tools/archiDART
- [x] https://bio.tools/Picopore
- [x] https://bio.tools/CyAnimator
- [x] https://bio.tools/ReactomeFIViz
- [x] https://bio.tools/DataUp
- [x] https://bio.tools/ROCKETSHIP
- [x] https://bio.tools/FANTEN
- [x] https://bio.tools/Dipcheck
- [x] https://bio.tools/Bamutil
- [x] https://bio.tools/cpc
- [x] https://bio.tools/treegraph_2
- [x] https://bio.tools/SAPP
- [x] https://bio.tools/w2rap-contigger
- [x] https://bio.tools/VizStruct
- [x] https://bio.tools/CCAT
- [x] https://bio.tools/AMEN
- [x] https://bio.tools/AMEN5516
- [x] https://bio.tools/AMEN2063
- [x] https://bio.tools/V-Pipe

**Comment by joncison** [comment]
Issues:
* DOI regex (allowing " doi" suffix)
* DOI regex (allowing "DOI:" prefix)
* PMC regex (not insisting on "PMC" prefix)
* "Note" length (shorter than 10 minimum)

**Comment by joncison** [comment]
well @hansioan - that was fun :-/

**Comment by hansioan** [comment]
@joncison 
nice work. I assume the issues were with the content, not with the actual validation which allows such things.

**Comment by joncison** [comment]
we need to double-check tomorrow in some cases (bit tired now for it)

**Comment by jaanisoe** [comment]
Nonvalidness of three tools might be caused by an issue I commented on under a closed (but not quite resolved) biotools schema issue: https://github.com/bio-tools/biotoolsSchema/issues/8.

Namely, the DOI regex is still too restrictive. That is, validation does not allow some actually valid Wiley DOIs.

The tools in question are:
- https://bio.tools/glycomod
- https://bio.tools/SeqMS
- https://bio.tools/radar

Seems that the DOIs have been truncated (e.g., for glycomod the correct DOI [10.1002/1615-9861(200102)1:2<340::AID-PROT340>3.0.CO;2-B](https://doi.org/10.1002/1615-9861(200102)1:2<340::AID-PROT340>3.0.CO;2-B) has become truncated as [10.1002/1615-9861](https://dx.doi.org/10.1002/1615-9861)). The correct DOIs can be seen in dev.bio.tools.

**Comment by joncison** [comment]
OK thanks ... we'll tackle this point @jaanisoe  [here](https://github.com/bio-tools/biotoolsSchema/issues/8) (now re-opened)
