### ISSUE TITLE
Try ELIXIR bio.tools logo 

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#391]
![elixir_biotools](https://user-images.githubusercontent.com/1506863/49898096-f1f46f80-fe4f-11e8-99f2-fde4b7520adb.png)

**Comment by scapella** [comment]
Jon,

Talk to the ELIXIR Hub because there are some guidelines regarding the
ELIXIR logo which have to be honoured.

Cheers,

Salva

**Comment by joncison** [comment]
Thanks, will do

**Comment by joncison** [comment]
![image](https://user-images.githubusercontent.com/1506863/49924558-986f5d80-feae-11e8-8398-7cddbf834ffe.png)
