### ISSUE TITLE
subdomain title and descriptions do no longer appear

### ISSUE THREAD

**Issue by lmatalonga** [bio-tools/biotoolsRegistry#396]
Hi, I've noticed that with the new release subdomain title and description do no longer appear https://bio.tools/?domain=rare-diseases 

Do I need to activate to do so? 
Thanks, 
Leslie

**Comment by joncison** [comment]
You may need to "force-refresh" your browser ...

**Comment by joncison** [comment]
I get this: 
![capture](https://user-images.githubusercontent.com/1506863/49991244-5ca0ca80-ff78-11e8-8fc6-1928481832bc.PNG)

**Comment by lmatalonga** [comment]
Thank @joncison, working now!

**Comment by joncison** [comment]
cool .... if you have ideas on what other community/subdomain-specific information could be given, please create a new issue for it.
