### ISSUE TITLE
Sorting by columns/attributes (grid view and cards view)

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsRegistry#4]
It's awesome that the default sorting is by modification date!
But:
- It should state 'modification' or so, instead of 'addition'
- There should be a corresponding column available in the grid view
- It should be possible to sort by ALL columns/attributes (otherwise hard to search for some stuff)

**Comment by joncison** [comment]
@matuskalas  - could you specify please which columns you'd like to sort by?

It's not really possible to search by all as some columns can have multiple values and the sort behaviour is not obvious in such cases

PS.  sort now has "Updated" and "Added"

As for "There should be a corresponding column available in the grid view" I created issues here:
https://github.com/bio-tools/biotoolsregistry/issues/141

**Comment by joncison** [comment]
giving this a nudge ... thanks
