### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by CaroleGoble** [bio-tools/biotoolsRegistry#402]
can we pleae make search intuitive, simple and work.

**Comment by joncison** [comment]
Thanks - but could you be a bit more specific please?  

how does it not work?  and how could it be made more intuitive and simple?  

We'll consider any suggestions for next release cc @hansioan

**Comment by CaroleGoble** [comment]
search collections is really confusing. how do I do that? how do I select a collection and then search within it? 

I type words into the search box and pres search and I do not get the answers

**Comment by hansioan** [comment]
An easy way to search for collections (as well as other properties) is to start typing a word in the search box (or minimum 2 characters) and you will start getting suggestions, which can be filtered by different properties (e.g. Everything, Topic, ..., Collection, Name). By clicking the Collection filter you will only get suggestions for existing collections in the dropdown and not for anything else. See the screenshot below:

<img width="1016" alt="collections_search" src="https://user-images.githubusercontent.com/12627065/51324034-f96bf180-1a69-11e9-9374-453c476db59b.png">
