### ISSUE TITLE
beta , alpha in tool name and id

### ISSUE THREAD

**Issue by hansioan** [bio-tools/biotoolsRegistry#411]
There are tools in bio.tools which have `beta`or `alpha` at the end of the name, I don't think this makes a lot of sense to store in the name, perhaps in the version. We at least need to keep an eye on these tools and update accordingly when the tool is not beta anymore.

Also, the tool ids should not have `beta` or `alpha` suffixes if the id without these suffixes is available.

Tools with alpha and beta in the name:

https://bio.tools/3d-blast
https://bio.tools/alphadrop
https://bio.tools/carthagene
https://bio.tools/cbcanalyzer
https://bio.tools/fungifun
https://bio.tools/genocrypt
https://bio.tools/gifi_array_analyzer
https://bio.tools/hicplotter
https://bio.tools/kegdraw
https://bio.tools/linksnps
https://bio.tools/metapepseq
https://bio.tools/mgcat
https://bio.tools/motifcut
https://bio.tools/neobio
https://bio.tools/oqtans
https://bio.tools/phylogeosim
https://bio.tools/proteinshader
https://bio.tools/romprev
https://bio.tools/sigma_align
https://bio.tools/snoopcgh
https://bio.tools/treq
https://bio.tools/typhon
https://bio.tools/youscope
https://bio.tools/zeus

@joncison

**Comment by joncison** [comment]
Agree completely.  We should fix these now (names and IDs) so that people get the message.  Also probably need a note in the Curation Guidelines along these lines ...

**Comment by joncison** [comment]
Excellent you found these.  They should also be labelled as "Emerging"

**Comment by hansioan** [comment]
Yeah, maybe some, but for example
https://bio.tools/youscope
is not emerging in my opinion.

Could be yet another check in the linter, or some sort of reminder to check that the `alpha` or `beta` labels are still there or can be removed

**Comment by joncison** [comment]
Ahh ...  I see.  So it would be a manual job to assign "Emerging"

**Comment by hansioan** [comment]
Well, I think so, at least at this point, because we don't really know if they are Emerging still...and the Emerging tag would have to be removed at some point. I'm not exactly sure when a tool is not Emerging anymore.

**Comment by joncison** [comment]
It's for the developer to say, really.  If it's a new tool which the author designates as "alpha", "beta" etc. it's "Emerging".   Everything else is "Mature" unless the author says its "Legacy" (obsolete).

**Comment by magnuspalmblad** [comment]
Agree for &alpha; and &beta;. However, it seems authors sometimes incorporate major version numbers in the tool name, e.g. EBprotV2 (https://www.ncbi.nlm.nih.gov/pubmed/30411623). Perhaps we can afford some discretion here? Some tool names also end with a number that has nothing to do with version numbers, e.g. compareMS2.

**Comment by joncison** [comment]
Yeah ... the guideline here is that if an author has branded their tool to include a number in the name _e.g._ HMMER3 - presumably because they want to convey it's a big step forward - then such a tool should have it's own entry with the name and ID preserving the number.    But general iterations of version numbers (where there can be many dozens for a single tool) for a tool are out of scope (although the author can record in the entry the version(s) for which the description is valid for.

And sure, compareMS2 is perfectly fine.

**Comment by joncison** [comment]
For now .... fixed in IDs but not in names.  Need a lint check for this!
