### ISSUE TITLE
Pub2Tools

### ISSUE THREAD

**Issue by jaanisoe** [bio-tools/biotoolsRegistry#427]
Initial discussion in the attached PDF [Pub2Tools.pdf](https://github.com/bio-tools/biotoolsRegistry/files/3006903/Pub2Tools.pdf).

One task would be to create an initial empty repo https://github.com/bio-tools/pub2tools and migrate Pub2Tools to it from https://github.com/edamontology/edammap/tree/master/pubmedapps.

**Comment by jaanisoe** [comment]
Pub2Tools version 1.0.0 has been released and is available from https://github.com/bio-tools/pub2tools.

Issues can be reported to https://github.com/bio-tools/pub2tools/issues.

**Comment by joncison** [comment]
Just want to say great work @jaanisoe - sorry for taking an age to get back about it.
