### ISSUE TITLE
unable to update rare disease domain

### ISSUE THREAD

**Issue by lmatalonga** [bio-tools/biotoolsRegistry#429]
Hi @joncison and @hansioan 

For some reason I cannot add resources to the rare-diseases subdomain nor update it (https://bio.tools/edit-subdomain/rare-diseases ) . The error is "Domain could not be created. Could not locate resource with id Knowledge.bio_LWAS ."

Thanks for your help.
Leslie

(related to HELP: rare disease domain is down #362) 

![image](https://user-images.githubusercontent.com/25792446/56582490-ad37cc80-65d7-11e9-84c6-7168e6dd6bc4.png)

**Comment by hansioan** [comment]
Hi @lmatalonga ,

It should be fixed now, it was a bug on our side with the tool ids. 
As a result of fixing the issue , the following tools were added to the rare-diseases subdomain:

https://bio.tools/esp
https://bio.tools/umd
https://bio.tools/emvclass
https://bio.tools/rd-connect_platform
https://bio.tools/knowledge.bio
https://bio.tools/epga

one of which is Knowledge.bio (LWAS).
If you don't want the others please remove them or let me know and I'll remove them.
You should be able to edit the subdomain now and add/remove tools without any issues. Please let me know if you still have issues.

Hans

**Comment by lmatalonga** [comment]
Hi @hansioan, 
Working now. 
Thank you very much!
Leslie

**Comment by joncison** [comment]
closing this now, cc @hansioan
