### ISSUE TITLE
Can a collection be used to describe a tool suite ?

### ISSUE THREAD

**Issue by albangaignard** [bio-tools/biotoolsRegistry#433]
@jvanheld

**Comment by joncison** [comment]
This is exactly how we're doing it currently (giving tools within a suite a common "collection" annotation) .. a bit crappy I know ... but see https://github.com/bio-tools/biotoolsRegistry/issues/431 (some better way to handle such relationships is needed)

**Comment by joncison** [comment]
@albangaignard @jvanheld 

we're putting the finishing touches to biotoolsSchema 3.1.0 which supports the definition of relationships between bio.tools entries.  So in future we'll be able to say someSuite _includes_ someTool, or conversely someTool _isIncludedIn_ someSuite

It'll hopefully be ready next week but there's some work to do still  ....

**Comment by joncison** [comment]
relations now implemented, so I close this cc @hansioan
