### ISSUE TITLE
The ORCID field does not accept an ID, and actually it expects an URL to the ORCID

### ISSUE THREAD

**Issue by albangaignard** [bio-tools/biotoolsRegistry#437]
@jvanheld

**Comment by joncison** [comment]
yeah ... that's wrong really

thanks !

will need to make a minor schema release to address these issues

**Comment by joncison** [comment]
fixed in biotoolsSchema ... change will filter through to bio.tools in due course

**Comment by hansioan** [comment]
I'm not sure ... the orcid.org website looks like they want urls in the id:

https://orcid.org/news/2012/08/02/what-does-orcid-identifier-look-like
https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier

**Comment by hansioan** [comment]
Quote from 
https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier

"
The ORCID iD is an https URI with a 16-digit number that is compatible with the ISO Standard (ISO 27729), also known as the International Standard Name Identifier (ISNI), e.g. https://orcid.org/0000-0001-2345-6789
"

**Comment by joncison** [comment]
Yup @albangaignard the "https" bit is mandated in the syntax, so this will be [reinstated in 3.1.0](https://github.com/bio-tools/biotoolsSchema/issues/144)

**Comment by joncison** [comment]
this now fixed in biotoolsSchema and bio.tools
