### ISSUE TITLE
Make pagination reasonable

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsRegistry#458]
Pagination with 10 items at a time is seriously ridiculous. Especially in the tabular view (btw. add back sorting #457), but also in cards view.

Either:

- Replace by "infinite" scroll

- Implement scrollable "See more" (as is nowadays usual in webapps)

- Increase the pagination to 100

- Give options for pagination (e.g. 25 and 100, or 3 options)

**Comment by joncison** [comment]
Yup, requested a lot.  See https://github.com/bio-tools/biotoolsRegistry/issues/111, https://github.com/bio-tools/biotoolsRegistry/issues/325, https://github.com/bio-tools/biotoolsRegistry/issues/76,

**Comment by matuskalas** [comment]
❤🙏🏽
