### ISSUE TITLE
Colours of buttons on Edit page

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsRegistry#470]
From @jvanheld & @joncison:

* **Save** button should be green
* **Validate** button an intermediate colour (blue? yellow? orange?)
* me: Add (a) **Back** / **View** / **Preview** / **Save & view** button(s)?

**Comment by hansioan** [comment]
I agree that the color green for validation is confusing, changed to orange now , more like a warning type of color.

Added a button to navigate to the tool card page.
