### ISSUE TITLE
Tool's owner

### ISSUE THREAD

**Issue by vincent-lefort** [bio-tools/biotoolsRegistry#472]
I would like to find a way to know each tool owner.
Here is my use case: I'm developing several phylogenetic tools. Some of them were already created in bio.tools. I don't know by whom. I'd like to contact that person.

**Comment by joncison** [comment]
@hansioan I think it would be nice to render the tool owner somewhere on the tool card.

In the meantime @vincent-lefort then, if you are the rightful "owner" of the tool, i.e. developed the software or provide an online service, then just go ahead an "Request ownership".  If you're not certain you should "own" the entries but want to edit them, you can "Request edit rights".

PS.  I created some boilerplate entries to ensure all FR tools submitted to the ELIXIR FR SDP had (at least) basic entries, so if your tool fits into that category, the current owner might be me.

**Comment by hansioan** [comment]
@vincent-lefort 
My apologises for the late response. The tool owner can be accessed via the API version of a tool, for example the JASPAR tool, you can access it at:
https://bio.tools/api/jaspar
and there is a property called "owner". 

That being said, you will only see the username of the owner and not their email, we don't give out other username emails. 

If you want to contact the developers your best chance is to look at the credits of a tool, that's where you can find information (including emails or urls) about who has been credited in relation to a tool. If you want to do it programmatically, you can access tools via the API as mentioned above and look at the "credit" property. 
To make sure you get the JSON rendering of the tool via the API add the ?format=json at the end, e.g. 
https://bio.tools/api/jaspar?format=json
