### ISSUE TITLE
Name of the tool, special characters "®" and "/" not accepted

### ISSUE THREAD

**Issue by skossida** [bio-tools/biotoolsRegistry#475]
Hello,
it would be nice to be able to use the "®" and the "/" symbols.

- IMGT®, the international ImMunoGeneTics information system®
- IMGT/StatClonotype 

Thank you for your efforts,
Sofia

**Comment by jvanheld** [comment]
The ID is automatically generated from the name when a new bio.tools is created. I would certainly not recommend to use @ and / in a tool ID, since it would create a mess for the URL (which is a concatenation of bio.tools + the tool ID). 

A trick (that Jon suggested for RSAT tools) is to  first create the tool entry with a name that will serve to build a suitable ID, and  afterwards modify the tool name for the display in the bio.tools record. Once assigned, the tool ID is stable irrespective of the changes of the name; 

This will avoid including @ and / in URLs (which is an obvious source of problems). 

Jon, would this trick be suitable to solve Sofia's request ?

**Comment by skossida** [comment]
Dear Jacques,

Thanks a lot for your prompt answer.
It is the ® symbol and not the at symbol.

On a different note, we are wondering if there is an automatic filtering to avoid duplications. Two of the IMGT tools share the same url. Does this cause an issue?

I suppose, please confirm, that there is not a big deal if the slashes are not visible, at this stage.

Thanks a lot again.

Best regards,
Sofia

**Comment by joncison** [comment]
Hey Sofia

I'll just extend a bit on what @jvanheld said.

The bio.tools ID is created for you at registration time and is _URL-safe version_ of the supplied tool name, *i.e.* all non-URL-safe characters are stripped out and replaced by underscore (```_```).

There are also restrictions on the tool name, including the ```®``` and ```/``` symbols.  We'll keep this issue open until @hansioan and me discuss this more.  The reason it's restricted currently (and likely will remain so) is to ensure trouble-free usage of the name in all sorts of technical contexts.  But I can appreciate this may be an issue for you.

If you want a name that includes non-URL-safe characters (so far as these are supported by the _Name_ field) then you can use the trick Jacques suggested:
1. create the entry - specifying the ID you want in the name field
2. save the entry
3. edit the name field to the name you want

It's perfectly OK for two tools entries to have common URLs, _e.g._ for homepage.

Hope this helps!

**Comment by skossida** [comment]
Dear Jon,

Sure, I fully understand the special characters and that they are cumbersome. The resources were created long ago and baptised by a non-informatician, if I was to justify a bit their choice. Appologies for the inconvinience.


  1.  > edit the name field to the name you want
I think, I’m missing something here, I’m afraid.I tried to reproduce your suggestion, but I still get an error. File attached.

I repeat, it would be better to live with the slashes and the R, however I can live perfectly well without.


> It's perfectly OK for two tools entries to have common URLs, e.g. for homepage.
Sure. Saw it in practice too.

Thanks a lot again.

Sofia

**Comment by skossida** [comment]
Dear Jon,

we added the name of the resource properly spelled, including the slashes, in the description of it. We think that this is a nice compromise.

Thanks a lot again for your help.

Sofia

**Comment by hansioan** [comment]
@skossida @joncison 
As Jon mentioned, special characters like ® are not URL safe and as it currently stands the IDs (which need to be URL safe) are generated from the name. We will soon remove this constraint, so the trick suggested will not longer be necessary. 

However, we have not discussed if special symbols like ® will be allowed in the name of a tool.

Thank you for the request

**Comment by skossida** [comment]
Hello,

Happy New Year &

Thanks a lot for your efforts.

Best regards,
Sofia

Professor Sofia KOSSIDA
University of Montpellier

IMGT®, the international ImMunoGeneTics information system®
http://www.imgt.org<http://www.imgt.org/>
IMGT, IGH, UMR 9002 - CNRS - UM
15 Av Charles Flahault
34090 MONTPELLIER, FRANCE
e-mail : Sofia.Kossida@igh.cnrs.fr<mailto:Sofia.Kossida@igh.cnrs.fr>

Doctoral School CBS2
https://edcbs2.umontpellier.fr/


[https://www.umontpellier.fr/wp-content/uploads/2014/12/Logo_MUSE_Original.jpg][https://edcbs2.umontpellier.fr/images/logo2.jpg][logo IMGT]
