### ISSUE TITLE
wrong publication

### ISSUE THREAD

**Issue by egonw** [bio-tools/biotoolsRegistry#481]
Looking at the DOI of the primary publication of BridgeDb, https://bio.tools/bridgedb, then I notice that the DOI is correct, but the article shown is the wrong publication. There seems to be something wrong with the DOI-article link in the record and/or bio.tools.

**Comment by hansioan** [comment]
I updated the publication information for 
https://bio.tools/bridgedb
and now it looks like it's working. 
Could be an error on the Elsevier side ...

**Comment by egonw** [comment]
thanks
