### ISSUE TITLE
remove tools

### ISSUE THREAD

**Issue by vincent-lefort** [bio-tools/biotoolsRegistry#482]
Hi, I found 2 entries for PhyML:
https://bio.tools/phyml
https://bio.tools/phyml_oneclick
Can you remove the last one? ('oneclick')

There is the same for FastME:
https://bio.tools/fastme
https://bio.tools/fastme_oneclick
Can you remove the 'oneclick' one?

**Comment by joncison** [comment]
found this in inbox nudge @hansioan

**Comment by hansioan** [comment]
Done
