### ISSUE TITLE
merge phylogeny.fr

### ISSUE THREAD

**Issue by vincent-lefort** [bio-tools/biotoolsRegistry#483]
There are 2 entries for phylogeny.fr:
https://bio.tools/phylogeny.fr
https://bio.tools/phylogeny.lirmm.fr

But they only are two mirror sites of the same service. Can you merge them and take care to keep both URLs?

**Comment by hansioan** [comment]
@vincent-lefort 
I would say keep 
https://bio.tools/phylogeny.fr
which has the homepage:
http://www.phylogeny.fr/

and remove the other since the first one already has the url:
https://bio.tools/phylogeny.lirmm.fr
as a Link type of Mirror

**Comment by vincent-lefort** [comment]
yes, it's ok for me

**Comment by hansioan** [comment]
Done
