### ISSUE TITLE
Change username placehodler in login window

### ISSUE THREAD

**Issue by duboism** [bio-tools/biotoolsRegistry#485]
The username placeholder in the login window is `username@example.com`. This let the user believe that he or she must use its email address to log in (while in fact the username is needed).

As en example, I changed my password 2 times right after creating my account because I was confused and thought I mistyped my password.

The placeholder could just be `username`.

**Comment by hansioan** [comment]
Done

**Comment by duboism** [comment]
Thanks for the super fast answer.
