### ISSUE TITLE
Support addition of tool logos

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#49]
Low priority, but this has been requested

**Comment by joncison** [comment]
This is supported in https://github.com/bio-tools/biotoolsSchema/tree/master/versions/biotools-2.0.0

**Comment by OlivierCollin** [comment]
This has been requested to me by the developer of a tool.

**Comment by joncison** [comment]
It would help to enhance the look of the website so we'll put this under consideration for the web site redesign that's scheduled for next year cc @ekry.  It would require standardisation of logo images, but I wonder whether we could leverage the ``<download><type>Icon</type></download>`` annotation auto-magically, _i.e._ if a tool is annotated as having a logo, we pull, transform and render.

**Comment by joncison** [comment]
nice to have but not a high priority for now
