### ISSUE TITLE
Ontology tree widget

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsRegistry#5]
A thread for gathering & discussing requirements for improving the usability of the ontology tree widget

**Comment by matuskalas** [comment]
In contrast to the very convenient and pretty rest of the bio.tools GUI, the ontology tree widget and the whole _Function_ tab are super inconvenient to use, to the extent of hampering extensive annotations.

Points for improvements follow, most of them regularly re-appearing as oral suggestions from various tools annotators.



### Selection of multiple concepts at once



### Hide the tree widget after done and going to another one
And open again when clicked.



### Show properties of the concept on hover
At least: definition, primary label, internal synonyms, related concepts (via relations including generalisation).



### Enable fully expanding the whole subtree
Using a different type of click.



### Usability optimisation of the filtering
Note: awesome that deleting the filter string keeps the tree open as is, just adds the previously hidden concepts!

Some brainstroming for further analysis, design, optimisation:
- analyse the plentitude of examples of other contemporary ontology tree browsers
- search for concepts separately, show in a popped-up dropdown (gmail|ncbo style)
- highlight found concepts instead of hiding the rest (search instead of filter)



### Add synonyms into the search
And later also relations between concepts, maybe also definitions, comments, _etc._



### The whole _Function_ tab in the bio.tools registration interface needs a visual clean-up
And probably at the same time a corresponding data model fix (_NB._ bio-tools/biotoolsxsd#2).

Otherwise very hard to see where a user is looking. Input? Output? Input format? Another function?

**Comment by matuskalas** [comment]
Please comment on the above, add +1s where applicable, and add further ideas.

**Comment by joncison** [comment]
@matuskalas  - many of these features are captured in the new Tool Annotator function - the thing we designed at the DK hackathon, which I then mocked-up and which @hansioan now has a good basic implementation (not yet integrated into bio.tools).  

I assign this to @hansioan to pick up on

**Comment by joncison** [comment]
This issue was moved to bio-tools/edamToolAnnotator#5
