### ISSUE TITLE
Operations lack epidemiologic options

### ISSUE THREAD

**Issue by ells** [bio-tools/biotoolsRegistry#510]
In light of the utlity for COVID-19, there are a number of options related to epidemiology that should be considered.

For example, options like 'contact tracing', 'contact network visualization', or 'transmission network' should be considered.

For example, bio.tools/microbetrace is ideal for visualization of contact tracing data but the available options do not allow us to highlight these capabilities of our tool.

**Comment by hansioan** [comment]
@ells 
Operations and concepts as the ones you mentioned should be part of the EDAM Ontology:
https://github.com/edamontology/edamontology/
which is what we use in bio.tools for annotating bioinformatics concepts

The EDAM Ontology has an Operation concept request GitHub issue page:
https://github.com/edamontology/edamontology/issues/new?template=new-operation.md

@joncison perhaps you can help more

**Comment by joncison** [comment]
Hi @ells 

It would be great if you could suggest any new EDAM concepts to cover the utility of COVID-19 related tools / methods.  

If you head to https://github.com/edamontology/edamontology/issues/new/choose you'll see options for the different major subontologies (Data, Format, Operation and Topic).  Each concept has slightly different information requirements, which are all hopefully obvious in the issue templates (which you'll see when you click on one of the  "Get started" links.  The more information that can be provided, the better.   

Cheers

Jon

PS. will migrate this to the EDAM repo

**Comment by joncison** [comment]
Hi @ells just giving this a nudge, please head over to https://github.com/edamontology/edamontology/issues and request any terms you need re epidemiologic options on your tools.  Thanks !
