### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by alaninmcr** [bio-tools/biotoolsRegistry#520]
The login for bio.tools is not working (for me). I have done a password reset; however it still does not let me in.

**Comment by hansioan** [comment]
@alaninmcr Make sure you are logging in using your username + password (not email + password). Did you use your username?

**Comment by alaninmcr** [comment]
Probably not. How do I find out what my username is?

**Comment by hansioan** [comment]
Your email ends in `.ac.uk` and the username si almost the same except it ends in `.ac.`. However you haven't logged since 2017 so perhaps there is another account you have. Maybe we should move the talk to email, please email us (check out the bio.tools footer for details)

**Comment by hansioan** [comment]
@alaninmcr great to hear :) , it's probably been truncated
