### ISSUE TITLE
PomBase entries need improvement

### ISSUE THREAD

**Issue by mah11** [bio-tools/biotoolsRegistry#530]
Hello,

A search for "Everything: pombase" retrieves these results:

PomBase
PomBase Motif search 
PomBase data slicer
PomBase VEP
PomBase assembly converter

Of these, only the first two should be associated with PomBase at all, and even those have out-of-date details.

- [PomBase](https://bio.tools/pombase):
  - The main URL, Credits & Support list, and Twitter link are correct.
  - In the topic list, "Biology" appears three times, and others could be added: "Genotype and phenotype", "Molecular interactions, pathways and networks", "Genetics", "Genomics", and probably more. Is there a list of topics to choose from?
  - The text description is accurate, but you could also use the text from the PomBase home page: "PomBase is a comprehensive database for the fission yeast Schizosaccharomyces pombe, providing structural and functional annotation, literature curation and access to large-scale data sets".
  - Most of the items in the input/tool operation/output graphic are a bit perplexing. By analogy with bio.tools entries for other MODs, we could keep the box with Data retrieval, Query and retrieval, Genome visualisation, and possibly Text annotation (although I'm not sure what that means). Inputs to "Query and retrieval" could include Gene ID, Protein identifier, Ontology term ID, and probably others (again, is there a list of options?)
  - The "General" Documentation link should be changed to https://www.pombase.org/documentation. We also have an FAQ (https://www.pombase.org/faq), a citation page (https://www.pombase.org/about/citing-pombase), a Terms of Use page (https://www.pombase.org/about/terms-of-use), and a privacy policy (https://www.pombase.org/about/privacy-policy) if any or all can be included.
  - Several publications are missing, and the one listed is not the best to call "primary". We recommend PMID:30321395 - DOI:10.1093/nar/gky961 for citing PomBase. All of the publications under the "Publications authored by PomBase staff" heading on this page could be included: https://www.pombase.org/about/published-by-pombase, or, if there is a limit on how many can be listed, let me know and I'll identify the best selection.
  - Also note that PomBase was connected with Ensembl Genomes in the past, but this collaboration ended over four years ago (likely revelant to the rest of the "pombase" search results in bio.tools).

- [PomBase Motif search](https://bio.tools/pombase_motif_search):
  - The URL should be updated to https://www.pombase.org/motif_search. (The old link shown is not dead, but does not link to documentation or anything else.)
  - Under Documentation, the http://www.ebi.ac.uk/about/terms-of-use link should be removed (it can be replaced with https://www.pombase.org/about/terms-of-use). The "General" documentation link can be more specific: https://www.pombase.org/documentation/motif-search.
  - Under Credits & Support - This tool is no longer available via either the Sanger Institute nor EMBL-EBI, so these items should be removed. The PomBase helpdesk email address appears twice as a "primary contact", once with and once without the label "PomBase".
  - This tool is not part of either the Ensembl Tools or EBI Tools collection.

- [PomBase data slicer](https://bio.tools/pombase_data_slicer), [PomBase VEP](https://bio.tools/pombase_vep), and [PomBase assembly converter](https://bio.tools/pombase_assembly_converter). For all of these, the same comments apply:
  - There is no such tool. All three are tools developed by, and accessible via, Ensembl; presumably they do (or could) have bio.tools entries in their own right. PomBase does not maintain its own instances of any of these tools.
  - Each of these pages includes a dead link (genomebrowser.pombase.org has not been a working URL since some time in 2017).
  - As far as I know, *S. pombe* data can be used with these tools via Ensembl Fungi, but they should not be associated with PomBase.
  - My best guess is that these "PomBase" entries should simply be removed from bio.tools, since they refer to non-existent tools.

Thank you,
Midori (on behalf of all the PomBase staff)

**Comment by ValWood** [comment]
;)

**Comment by mah11** [comment]
edited item for PomBase Motif Search in original summary

**Comment by hansioan** [comment]
@mah11 Thanks you for the very thorough post and also for the edits.

You are right that there are issues with the annotations and things need fixing. 
Would you consider making the edits? I am asking because there are over 20,000 tools in bio.tools and it is hard to maintain the content. Furthermore, I believe that entries in bio.tools would be best maintained by the devs / curators / researchers closest to the tool as they have the most knowledge about the tool. 
If this is something you would consider we can happily help on our side with anything you need. 

Regarding the tools with the dead links. Here we can maybe have a discussion on what to do with them but deletion is probably not the solution, we don't want to lose the IDs (also bio.tools links) which we advertise as being persistent once verified. There are a number of solutions here, either redirects, marking as deprecated etc. We can even change the name 

Thanks,
Hans
@bio.tools

**Comment by mah11** [comment]
@hansioan Thank you for the response. 

> Would you consider making the edits? 

For the current PomBase site and tools, yes, I'm willing to edit the entries, although there's a good chance I'll have questions or require assistance somewhere along the line. Please let me know how to get started.

If all goes well, I could also create an entry for our online curation tool, Canto (https://curation.pombase.org/; PMID:24574118).

> Regarding the tools with the dead links.

I suggested removing the entries because there not only isn't, but never really was, a "PomBase" tool distinct from what's available via Ensembl Fungi (and if the entries were verified, that seems like an error). If there are entries for the corresponding "generic" Ensembl or Ensembl Fungi data slicer, VEP, and assembly converter, the existing PomBase entries could perhaps be merged into or redirected to them. If there is none, the PomBase entries can be renamed and repurposed. In either case, I could not take on editorial responsibility, because I have no connection with any of them; I'm probably not even the best person to choose from among the options.
