### ISSUE TITLE
Request editing rights fails

### ISSUE THREAD

**Issue by alaninmcr** [bio-tools/biotoolsRegistry#531]
I am trying to request editing rights on https://bio.tools/partsgenie however it gives:

_Failed to request editing rights for this tool. Check your internet connection and try again._

which is not correct as my internet is fine

**Comment by alaninmcr** [comment]
This happens in Chrome and in Firefox

It happens for https://bio.tools/selenzyme as well

**Comment by hansioan** [comment]
Please let me know what is your bio.tools username either here or by email at: registry-support@elixirmail.cbs.dtu.dk
