### ISSUE TITLE
IBISBA community

### ISSUE THREAD

**Issue by alaninmcr** [bio-tools/biotoolsRegistry#532]
Hello. I would like to create an IBISBA community on bio.tools

**Comment by hansioan** [comment]
Hello and apologies for the late reply.

What do you have in mind?
Do you want to create a page with details about the community and tools used by the community?
If so then the current model we have is to create a bio.tools domain at (account + login required):
https://bio.tools/edit-subdomain/

and add details about the community (currently some HTML tags are supported in the description field) + the tools relevant for the community.

Let me know if you need help with anything.
