### ISSUE TITLE
JSON validation error: "Only a superuser can remove a resource"

### ISSUE THREAD

**Issue by Dfupa** [bio-tools/biotoolsRegistry#544]
Hi,

I've been trying to remove a resource our lab owns (it has been duplicated), but whenever I tried to do it with the account that manages both resources, the following JSON validation error is displayed:

{
  "detail": "Only a superuser can remove a resource."
}

Can't the account administrating those services remove them by themself? If not, can I request the removal of said resource?

**Comment by hansioan** [comment]
Hi @Dfupa 

Please let me know the resource you want to remove and I will remove it.

**Comment by Dfupa** [comment]
Hi @hansioan

I've sent it to your github email contact hans@bio.tools with this issue's number and title as the subject of the mail
