### ISSUE TITLE
Update documentation link on the QuickNII sw

### ISSUE THREAD

**Issue by Majpuc** [bio-tools/biotoolsRegistry#551]
Dear elixir team,

Thank you for indexing our tool in your database. I was wondering if it would be possible to update the documentation link as we have recent readthedocs links that are more updated https://quicknii.readthedocs.io/
We also have extensive information for our users on these pages: https://ebrains.eu/service/quicknii-and-visualign

Also if possible could you add a line in the "credit and support"? The name is correct and should be kept. If possible add following text: "QuickNII is developed by the Neural Systems Laboratory at the Institute of Basic Medical Sciences, University of Oslo, Norway. QuickNII was developed with support from the EBRAINS infrastructure, and funding from the European Union’s Horizon 2020 Framework Programme for Research and Innovation under the Framework Partnership Agreement No. 650003 (HBP FPA)"

Thanks!
Best, Maja

**Comment by hansioan** [comment]
Dear @Majpuc 

I have updated the documentation link.

I would like to mention 2 things:
- The credit text is quite long and we only have a  `note` (i.e. comment)  field for a credit instances, so I took the liberty to add multiple credit instances for Neural Systems Laboratory, EBRAINS and Horizon 2020 with the right roles (e.g. developer, support, funding)
- I see that there there is no good owner for this tool, would you or someone else request ownership for this tool? It would be much better if someone who is involved in this tool could also own the bio.tools annotations for this tool. In this way one can fix/update the information without having to create an issue on GitHub

Let me know what you think
Thanks,
Hans
