### ISSUE TITLE
Link previews are inconsistent - angular not processed for most link previews.

### ISSUE THREAD

**Issue by hexylena** [bio-tools/biotoolsRegistry#552]
Hey y'all

link previews (e.g. as on twitter, matrix, etc.) seem to currently show relatively useless link previews in most places, due to the use of angular properties which are not resolved until javascript runs. Most link preview generators will only look at the HTML and not execute javascript, so replacing the following with their static alternatives would be useful:

```
	<meta name="description" content="{{ngMeta.description}}" />
	<meta property="og:title" content="{{ngMeta['og:title']}}" />
	<meta property="og:description" content="{{ngMeta['og:description']}}" />
	<meta property="og:image" content="{{ngMeta['og:image']}}" />
```

If you all would be up for filling those out statically (or at build time) it would result in a better user experience, I think!

Matrix | Twitter | Telegram
--- | -- | ---
![image](https://user-images.githubusercontent.com/458683/170994648-82c0be92-959f-41ed-8846-d636350ccfed.png) | nothing | ![image](https://user-images.githubusercontent.com/458683/170994908-a8916e38-1732-4837-aa54-07e2ef6d7942.png)

**Comment by hansioan** [comment]
@hexylena You are right that JavaScript needs to run to resolve those values.
However we have a server side generated page which is being served to robots, perhaps we're missing some.
I know the previews work on Slack for example

<img width="485" alt="bio tools preview slack" src="https://user-images.githubusercontent.com/12627065/170995982-75cd7cb8-07c3-4f2b-bfb9-16b62b4b147e.png">

So it doesn't work on Twitter and Matrix?

**Comment by hexylena** [comment]
Ahh interesting, ssr. That makes sense. Then yes, it's just matrix and twitter I think.
