### ISSUE TITLE
500 Server Error for open-specy

### ISSUE THREAD

**Issue by hmpf** [bio-tools/biotoolsRegistry#556]
This gives a 500 Server Error: https://bio.tools/api/tool/open-specy/?format=json

This works fine but returns 2 entries, not 1: https://bio.tools/api/t/?biotoolsID=%22open-specy%22&format=json

Looking at the result for method 2 the two results look identical apart from additionDate and lastUpdate. This looks like insufficient input validation to me, that the same record has been added twice.

**Comment by hansioan** [comment]
@hmpf 
Somehow it got duplicated in our DB and that's why you got the 500 Server error and the 2 entries. 
Fixed now, thanks for raising this issue.
