### ISSUE TITLE
Segmentation fault when running Weeder 2.0 locally

### ISSUE THREAD

**Issue by YangLi-Bio** [bio-tools/biotoolsRegistry#567]
Dear staff,

I have succeeded in running Weeder 2.0 for motif finding for many times, but today I came across such an issue:
>chr1:713995-714012	1\66146/var/spool/slurmd/job16508269/slurm_script: line 10: 197762 Segmentation fault      (core dumped) ./weeder2 -f /fs/scratch/PCON0022/liyang/CEMIG_full_assessment/Weeder/$TF_ID.fa

Could you please help me to figure out this issue?

**Comment by veitveit** [comment]
We are registry for software tools and not the developers of the tools. Please ask the developers of Weeder.
