### ISSUE TITLE
Wrong paper shown with correct link

### ISSUE THREAD

**Issue by fehrhart** [bio-tools/biotoolsRegistry#568]
![Clipboard02](https://github.com/bio-tools/biotoolsRegistry/assets/11389574/5823df83-4137-4607-814e-8ad2d26d607d)

It looks like the link to the BridgeDb API has a literature citation that does not match: https://dx.doi.org/10.1186/1471-2105-11-5 (on the page: https://bio.tools/bridgedb_api ) Interestingly - the DOI links correct to the bridgeDb citation - but it shows the title and abstract of a different paper on the page.

**Comment by veitveit** [comment]
As this does not seem to happen for other papers, this is not likely to be a bio.tools related issue. 

I changed to PubMed ID for now and it shows the right paper.
