### ISSUE TITLE
User interface problem with other ID type DOI: leads to RRID

### ISSUE THREAD

**Issue by erincalhoun** [bio-tools/biotoolsRegistry#572]
Under Update tool: Labels: Other ID I can add type doi and everything looks fine:
![image](https://github.com/bio-tools/biotoolsRegistry/assets/124356762/83f02b50-de78-4185-9a1c-c46f76b545e5)

But the main page shows it as RRID:
![image](https://github.com/bio-tools/biotoolsRegistry/assets/124356762/7781eb40-829f-47d6-8a9a-41fec4de4086)

and the link leads to a "not found" page on scicrunch.org:
![image](https://github.com/bio-tools/biotoolsRegistry/assets/124356762/68efd8c2-66a3-4a51-ad11-8a2535c68cc6)

**Comment by veitveit** [comment]
Strange and hopefully no but. What happens when you remove the "DOI:" from the value of the doi?

**Comment by veitveit** [comment]
OK, this is a bug. For now, I do not recommend to use the Other ID for anything else than for SciCrunch IDs, sorry. 

We will work on it but this will take time as we currently do not have an active developer.
