### ISSUE TITLE
Bio.tools down

### ISSUE THREAD

**Issue by Federico77z** [bio-tools/biotoolsRegistry#575]
The bio.tools website appears to be down, or better the DNS does not resolve it. It's got a "clientHold" EPP flag.

**Comment by veitveit** [comment]
Confirmed. We are working on getting access to the server again. Hopefully soon as this is a bigger issue.

**Comment by veitveit** [comment]
Yeah, sorry about that. I have not much influence on this rather than trying to reach somebody.

**Comment by veitveit** [comment]
Maybe use this intermediate version to create the json files for later upload to the "real bio.tools"?

**Comment by Federico77z** [comment]
mmhm no since my account does not look to work on the dev version. But ok, don't worry. I'll use today as an introduction and reschedule the meeting if somebody will need help when the official site is up and running. Thank your for your patience.

**Comment by veitveit** [comment]
Please make a new account. Account information is in the sql only and currently not accessible.

Any issues, please reach out as we are testing this one to become the main server.

Thanks!

**Comment by veitveit** [comment]
And you can request access to the tools you want to have updating rights.

**Comment by veitveit** [comment]
Update: I just was informed that you can access the actual bio.tools via https://130.226.25.21/
