### ISSUE TITLE
Daily operation of Bio.tools?? Plus how to handle requests?!?

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsRegistry#577]
Hey folks, who is responsible for handling this?
![image](https://github.com/bio-tools/biotoolsRegistry/assets/992660/3eb6f822-8784-458b-ad21-0856c2b1733e)
This clearly shows that the system of requests has to change. The only thing I can do is to grant all, as I don't have the capacity to review any of them. And I only see them if I happen to look at Bio.tools, what isn't part of my day-to-day job. So:

- [ ] Add notifications to email about the requests (not only to hans@bio.tools)
- [ ] Define who gets those emails (all curators/power-users?)
- [ ] Otherwise just grant all automatically and skip the Requests altogether (we anyway have to switch to GitHub workflow asap (due long ago))

**Comment by magnuspalmblad** [comment]
I suppose anyone who is associated with ELIXIR could be granted editing rights automatically? I would be a bit more cautious with doing it automatically for everyone (if memory serves someone did create spurious entries on bio.tools in the past). And ownership should probably be approved.

**Comment by matuskalas** [comment]
> I suppose anyone who is associated with ELIXIR could be granted editing rights automatically? I would be a bit more cautious with doing it automatically for everyone (if memory serves someone did create spurious entries on bio.tools in the past). And ownership should probably be approved.

We could think about a complex system like this, but first and right now we have to keep in mind that:

- For reviewing the requests, there simply isn't any workforce
- We have to move the whole contribution & ownership management to GitHub and pull requests, anyway. Rather overdue
- Detailed implementation of code ownership etc. should then be done at the level of Git paths (folders) or even files on GitHub

**Comment by veitveit** [comment]
@matuskalas @magnuspalmblad  
_Requests_:  
I think we have that quite well under control for now as requests are handled by us on a quite regular basis, and we do not have any now. But: when going through the requests, one has to decide about them only on basis of the login name. I  created a separate issue for this: #580 

_Access rights_:   
I would opt for a smaller group of people. New admins can rather easily be added. 

_Ownership & contribution ownership_:   
Not sure, how much work moving this to github would be. And Github is not everyone's thing, thinking for instance about PIs. And as first step, we need to have a go regular synchronization of the database in place. 

I will close this issue and create other ones
