### ISSUE TITLE
Stats showing a wrong year?

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsRegistry#578]
Is the year wrong in most of the plots? Or is there an even bigger bug? **This is detrimental to the PR and reporting!!!**
![image](https://github.com/bio-tools/biotoolsRegistry/assets/992660/dbd66dba-54a2-4d95-b888-4e3792faae8e)

**Comment by matuskalas** [comment]
> It definitely looks as if the year on the horizontal axes of all but one plot is off by one year. The number of entries (29,331) is recent, not January 2023.

That's exactly my impression, too.

Are quick fixes of this kind impossible now? @veitveit

**Comment by veitveit** [comment]
I assume this can be easily fixed as soon as bio.tools has finally been moved.

**Comment by veitveit** [comment]
The statistics apparently have been updated previously using celery. I can see that all celery-related code is commented out now. 

For updating the tool statistics, one needs to run the function _generate_missing_stats()_ in https://github.com/bio-tools/biotoolsRegistry/blob/master/backend/elixir/tasks.py

I will add a command for running it via _manage.py_, but we need to solve regular tasks, see #584
