### ISSUE TITLE
Specify output type as flag on URL

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#58]
From integration with INSTRUCT ...

"It would be nice to be able to specify the output type as a flag on the URL rather than having to send a HTTP-Accept header, simply because XMLReader (as far as I can see) has no way of defining context during a remote XML pull parse, and as such I always get JSON returned."

Chris Morris says ... "especially support the proposal to add a parameter for output type. I have found this very useful for debugging all sorts of services. I wish that there was a standard parameter for this, but in the absence of one I suggest “Accept=”. The semantics are that it overrides the Accept header, so the values should be as presented here:     http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html   

Callum says ... "I guess the HTTP Accept header is the closest to the "convention" so I wholly agree with the query string variable being named similarly. I really wish PHP was more procedural with it's development sometimes, (needle, haystack) or (haystack, needle), back to the documentation..., context or no, it seems a bit inconsistent. In any case I'm managing to specify headers but not with a pull parse,and as such having to load entire XML into memory, which is fine for now, but we may hit issues if the tool database grows big."

**Comment by joncison** [comment]
@ekry - there are a couple of issues here.  Please take a look and tell me if we can close this

**Comment by joncison** [comment]
@ekry @hansioan : was this done / can we close this?

**Comment by hansioan** [comment]
I'm not sure I understand what this means, does it mean the output type of results (JSON , XML)? 
Using the API, one can have 3 different formats which one can specify in the query string:

E.g.:
`https://bio.tools/api/t/SignalP?format=json`
`https://bio.tools/api/t/SignalP?format=xml`
`https://bio.tools/api/t/SignalP?format=yaml`

This stuff is also described in the API documentation

**Comment by joncison** [comment]
this done:
for "?format=json" 
for "?format=xml" (which will give biotoolsSchema 3.0.0 compliant XML)
