### ISSUE TITLE
suggesting changes for bio.tool entries, e.g. itol license information changed

### ISSUE THREAD

**Issue by magelm** [bio-tools/biotoolsRegistry#581]
Hi, 
https://bio.tools/itol says free of charge, but itol currently only offers a [paid plan](https://itol.embl.de/pricing.cgi)

Can this information be updated, please?
And is there a template to suggest small content changes like this without needing to request edit rights?

Thank you!

**Comment by magnuspalmblad** [comment]
I just logged in to iTOL (https://itol.embl.de/) with my Google account (using the "Sign up via external services" option) and could upload and render a tree from a Newick file without issues:

![image](https://github.com/bio-tools/biotoolsRegistry/assets/16084125/b04cd436-b2b1-4bf7-9af2-52271bfd56d1)

So no need to create a dedicated account or purchase a plan. Maybe the free version has limitations, but it has at least useful functionality in the free version.

**Comment by magnuspalmblad** [comment]
The free and paid plans are described on https://itol.embl.de/infoReg.cgi?f=p. So the cost label should be changed to "Free of charge (with restrictions)".

**Comment by veitveit** [comment]
I changed it now. Feel free to request editing rights and change these yourself.
