### ISSUE TITLE
wrong program and documentation links for BATMAN

### ISSUE THREAD

**Issue by daisymut** [bio-tools/biotoolsRegistry#582]
This page https://bio.tools/batman shows a description of a Bayesian tool for methylation analysis and is the one described in the associated publication but the [link ](http://batman.r-forge.r-project.org) points to the website of a different program with the same name but with a completely different application: an R package for estimating metabolite concentrations from Nuclear Magnetic Resonance spectral data. 
Also the reported link to [Documentation ](https://r-forge.r-project.org/scm/viewvc.php/*checkout*/documentation%20and%20test/batman.pdf?root=batman)is broken 
I was looking for the methylation tool and I am failing to find it, the link in the paper is old and not existing anymore

**Comment by veitveit** [comment]
This is well possible, as some of our entries unfortunately are not in shape. 

@daisymut Feel free to request editing rights and correct this.

**Comment by anitamnd** [comment]
Looks like the tool does not exist anymore so it has been removed from bio.tools.
