### ISSUE TITLE
help@bio.tools email address does not work 

### ISSUE THREAD

**Issue by carissableker** [bio-tools/biotoolsRegistry#591]
Received a server error in reply:

    Remote Server returned '554 4.4.1 < #4.4.1 X-Postfix; connect to bio.tools[130.225.156.21]:25: Connection timed out>'

At "Contact us" is an updated email address (@sdu.dk), but help@bio.tools is still listed as the contact on https://bio.tools/communities.

**Comment by veitveit** [comment]
Thanks for spotting this one. help@bi.tools does indeed not work anymore and we will change it to the new one "support-bio-tools@sdu.dk" at the next update.
