### ISSUE TITLE
Make better use of publication IDs (high priority!) (from Anne Wenzel, Kenzo etc.)

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#60]
e.g.. hover over a publication ID gives copy-pastable citation, title, abstract, impact factor of the journal etc.

This has been requested a lot !

**Comment by joncison** [comment]
Matus says ...
I'd personally love also a hack that pulls the fresh number of citations per each article from both Google Scholar and from PubMed Central (hopefully they have Web services fro that), best with graph of the citations over years (that shows whether the popularity is growing or shrinking; with the current year scaled up 365..366-div-today times)

**Comment by magnuspalmblad** [comment]
Europe PMC has a Web Service for getting the number of citations of a paper in PubMed - the _searchPublications _method returns the number of citations (within PubMed?) in the _citedByCount _element. See https://europepmc.org/docs/EBI_Europe_PMC_Web_Service_Reference.pdf for more information.

**Comment by khillion** [comment]
As Anne said, it can easily get huge and messy if we display the full reference instead of **DOI**, **PMID** or **PMCID**. What we could do is only display something like:

* First author *et al*, year, journal

And hover over would display full reference with different options and information you mentioned too.

**Comment by joncison** [comment]
Anne says ..."Re: Tool cards:
I like the idea of displaying publication info instead of just the PMID/DOI; it’s certainly more informative, however it can easily get huge and messy."

**Comment by joncison** [comment]
**UPDATE**
Near-term (2017 Q3-Q4) plans are:

* Pull in #citations from EuropePMC REST API including mechanism for update / cacheing of literature data
* Support AltMetric bookmarklet from AltMetric API
* Sorting by #citations and AltMetric attention score (https://github.com/bio-tools/biotoolsregistry/issues/106, https://github.com/bio-tools/biotoolsregistry/issues/35)
* Sorting by publication date
* Graph of #citations, altmetric etc. vs. time
* Pull in basic metadata for a publication, as per PDB (incl. copy-pastable citation information)
* Display basic metadata for a publication (from above)

cc @matuskalas FHI

**Comment by joncison** [comment]
**UPDATE**
Following are done:
* pull in #citations from Scopus 
* support AltMetric bookmarklet from AltMetric API
* sorting by #citations and AltMetric attention score (#106, #35)
* sorting by publication date (#35)
* graph of #citations, vs. time (done in https://github.com/bio-tools/biotoolsSum)
* pull in basic metadata for a publication, as per PDB (incl. copy-pastable citation information)
* display basic metadata for a publication (from above)

to do:
* use EuropePMC REST API for pulling  literature data (https://github.com/bio-tools/biotoolsRegistry/issues/360)
* sorting by AltMetric attention score (#35)
* incorporate "rising stars" (citations over time) into GitHub (https://github.com/bio-tools/biotoolsRegistry/issues/210)

cc @magnuspalmblad @khillion @matuskalas FTI (if you have other ideas around this, please post them as separate issues)

**Comment by joncison** [comment]
this would include rendering citation count & last publication date counts on tool mini-cards

**Comment by joncison** [comment]
rendering of publication information has been further improved (*e.g.* altmetric and dimensions widgets for individual publications, not just "primary") ... changes to be pushed tomorrow hopefully.

**Comment by veitveit** [comment]
We have altmetrics and OpenEBench integration.
