### ISSUE TITLE
Support "smart" links in Query Interface (links that act as filters)

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#63]
Such that clicking on link filters what you see.  Could do this for e.g.

EDAM Function, 
EDAM Topic
Provider 
etc

**Comment by joncison** [comment]
Alternatively, the links to a Function, Topic etc. could bring up the relevant bio.tools sub-pages listing all tools with that Function or Topic:

bio.tools/functions/sequence_alignment
bio.tools/topics/proteomics
etc.

Or provide both options (filter, or link to pages) as a pop-up menu upon hover-over the link

**Comment by joncison** [comment]
We have links for EDAM terms, nice to have these for credits too (more a search rather than filter)

**Comment by hansioan** [comment]
now with credit name search too.
