### ISSUE TITLE
idconvert

### ISSUE THREAD

**Issue by magnuspalmblad** [bio-tools/biotoolsregistry#77]
tool name:idconvert
short description: A converter between pepXML and mzIdentML formats for peptide identifications from tandem mass spectrometry. Developed by the ProteoWizard team.
URL:http://proteowizard.sourceforge.net/tools/idconvert.html
topics: topic_0121|topic_0134
term: operation_0335
input format: format_3475|format_2332
output format: format_3475|format_2332
synonyms: none
suggested parent:ProteoWizard
license: Apache License V2.0

**Comment by joncison** [comment]
Sorry @magnuspalmblad I got cross-wires in email. 

You can register this tool yourself directly in https://bio.tools/.  Click the "log-in" (top-right) and create yourself a private account.  Let use know (registry@elixir-dk.org) if you have problems.

**Comment by magnuspalmblad** [comment]
OK - my gmail account was not on the "whitelist", so I had to register with my LUMC e-mail account. 

But I managed to add the tool and fill out most of the fields. However, I could not find pepXML in the list of formats, only mzIdentML. This means the annotation is currently incomplete!

**Comment by veitveit** [comment]
Strange, I found it here
http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fformat_3655
Maybe bio.tools did still not update to the newest EDAM release?

Generally, it would be sufficient for now to add the tool to Ms-utils. It
will then be added to bio.tools together with all the other tools.

Cheers
Veit

**Comment by joncison** [comment]
Please mail registry@elixir-dk.org asking to bump support of EDAM to 1.14.  It will help to have "external" requests such as this to the list ... sorry this is cumbersome, bio.tools urgently needs fixing in this regard

**Comment by magnuspalmblad** [comment]
Dear All,

Regardless, it was a useful exercise for me to see how it works. When the new formats are there, I can use it as a practise for how to update a tool.


Cheers,

Magnus

**Comment by magnuspalmblad** [comment]
OK, e-mailed registry@elixir-dk.org with this request.
