### ISSUE TITLE
MG-RAST mis-spelt in tools registry

### ISSUE THREAD

**Issue by rdfinn** [bio-tools/biotoolsregistry#78]
MG-RAST is spelt as MG-MAST in the tools registry.  While I do not mind the slur on the competing resource, it does not look great.

https://bio.tools/?q=Metagenomics

P.S. - Current feedback system sucks!

**Comment by joncison** [comment]
typo fixed a while back

feedback currently via GitHub, registry-support mailing list (see http://biotools.readthedocs.io/en/latest/contributors_guide.html), with buttons to link to these soon, from UI (see https://github.com/bio-tools/biotoolsregistry/issues/146)
