### ISSUE TITLE
(All-hands2016-wp1)  consider including incompletely-annotated tool

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#79]
Exposing these to motivate improvements on the annotations

**Comment by magnuspalmblad** [comment]
Do we have a metric for this, or is it the annotator who decides that a tool is completely annotated? It is hard to know when an annotations is complete for tools that can perform multiple operations on data in more than one format. Or is an annotation considered complete when there is at least some annotation in each mandatory (asterisked) field?

**Comment by joncison** [comment]
The biotoolsXSD (the bio.tools schema) defines some attributes as mandatory.  Others (although this not defined in the XSD) are "recommended" or "optional" : so that's the basic metric I think.

**Comment by joncison** [comment]
Since this post, we lowered the information requirement for "unverified" entries at least, and "LinkedIn-style entry completion percentage" is in the roadmap for 2017 Q3.  This will be based upon (weighted) field completion, rather than "scientific completeness" of annotation.

**Comment by joncison** [comment]
Footnote for @magnuspalmblad, a formal information standard is on the way, see https://github.com/bio-tools/biotoolsSchema/issues/77 (comments there welcome)
