### ISSUE TITLE
Describe how publication should be provided in the registration form

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#8]
(moved from https://github.com/edamontology/edamontology/issues/39)
It would be useful having hints for what is expected in the registration form. For example, for publications, should these be *doi numbers *pubmed ids \* citations in txt?

**Comment by khillion** [comment]
Previous version of bio.tools contained one unique field where we could put one of the 3 ID (doi, pmid or pmcid). Now we have 3 text boxes and this can be confusing and less straightforward.
Would it be possible to get back to something similar ? By specifying any of the ID, information would be directly obtained by online resources, with for instance a preview of the publication (title, authors...).

**Comment by joncison** [comment]
There are now separate fields for DOI, PMID and PMCID.

Soon, tool tips will be added on those fields to clarify the syntax

**Comment by joncison** [comment]
@khillion this has been greatly improved and staged for release

**Comment by hansioan** [comment]
Example screenshot:

<img width="1234" alt="publications" src="https://user-images.githubusercontent.com/12627065/45163160-f6294500-b1ef-11e8-9787-e9669a1697f0.png">
