### ISSUE TITLE
(All-hands2016-wp1) consider alternative ways (graphical) ways to browse bio.tools

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#81]
Graphical alternatives to text-based / search box, e.g. via workflow, topics

**Comment by magnuspalmblad** [comment]
For examples/inspiration, see e.g. the [ExPASy Visual Guidance](http://www.expasy.org/vg/welcome), [OMICtools](http://omictools.com/) or [myExperiment](http://www.myexperiment.org/workflows).

Why not generate something automatically from the annotations in a clever way? :)

**Comment by joncison** [comment]
We have "Visual Workflows" mock-up mooted for 2017 Q3 and an icon-based navigation for beyond 2017 in the roadmap:
http://biotools.readthedocs.io/en/latest/changelog_roadmap.html

**Comment by joncison** [comment]
Just an update @magnuspalmblad, I'm very keen we embed the "visual workflow" idea into bio.tools, but first a bit more work is needed amongst the communities to define those workflows (such as we've been doing for proteomics - which could be the exemplar).   Right now we don't have the dev. capacity to implement anything in bio.tools though.
