### ISSUE TITLE
URGENT

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#86]
Rodrigo (EBI) says ...

"The following URL is still working for downloading the registry in XML:

url -H Accept: application/json -X GET https://bio.tools/api/tool

Question is if it will be maintained in order to set it up as part of an automatic pipeline?"

@ekry  please reply to this post here, and let Rodrigo know

**Comment by ekry** [comment]
The URL will most likely remain the same, however we have plans to enforce paging when returning the list of resources. The way I envision it, this request will return an object with at least URLs of the previous and next page and a list of resources for the current page. This will be documented in our upcoming documentation. So unfortunately it will require some adjustment, but hopefully not a major one. We will inform you before this goes into effect.
