### ISSUE TITLE
Rename 'Github page' to 'Source-code repository' and other small helpful fixes

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsRegistry#92]
Rename **Github page** to **Source-code repository**.

Add mention of **URL** to all **Documentation** fields.

Add mention of **DOI (preferred), PubMedID, or 'None'** to **Publication** fields.

**Comment by joncison** [comment]
@matuskalas ... could you clarify please what action to take here ?

**Comment by joncison** [comment]
@matuskalas is the appropriate action here to update the comments in biotoolsSchema.xsd as necessary?  These will eventually be exposed in the bio.tools UI as tool tips (see https://github.com/bio-tools/biotoolsregistry/issues/121)

**Comment by joncison** [comment]
@matuskalas - just giving this a nudge.  Could you clarify what you want please?

**Comment by joncison** [comment]
I think this is all fixed now, or no longer relevant, cc @matuskalas but pls. reopen / clarify as needed
