### ISSUE TITLE
BUG: registration is failing with Internal server error

### ISSUE THREAD

**Issue by mvdbeek** [bio-tools/biotoolsregistry#94]
I'm trying to register through the web interface, but there are multiple problems.
 - No error is shown (even through a 500 response comes through!)
 - Trying to register a second time says "email address already exists"

This is the payload
```
{"email":"mvdbeek@gmx.de","username":"test name","password":"test1234","repeat_password":"test1234"}
```

**Comment by mvdbeek** [comment]
Apparently it did succeed, I can login now, but the error handling is very bad.
At least the internal server error should be shown to the user.

**Comment by ekry** [comment]
This is now fixed. We are working on a complete rewrite of the account system, which will address most of such issues.
