### ISSUE TITLE
Handling deprecated EDAM concepts (silent fix)

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsRegistry#98]
Copy & pasted from what appeared after trying to save a resource:
(Notably, this part of the record hasn't been edited. Record is 'FreeSASA')

There was an error saving the resource.
Invalid functionName URI: http://edamontology.org/operation_1824
Data attached to error:

{
  "functionName": {
    "term": "Protein surface calculation (accessible)",
    "uri": "http://edamontology.org/operation_1824"
  }
}

**Comment by ekry** [comment]
This is most likely not a bug, but due to the term being deprecated in EDAM 1.14 to which we migrated bio.tools today. The new API (WIP) will inform about deprecated terms in error messages. We are also working on streamlining the incorporation of EDAM releases into bio.tools and the timeframes of that, along with putting information about the currently used release somewhere on the website.

**Comment by matuskalas** [comment]
Thanks @ekry, I see. Great to hear that updates of EDAM in Bio.Tools are being streamlined!

The obvious user experience enhancement should then in the first stage be to inform about a concept being deprecated, instead of "Invalid functionName".

The next step of improving experience should be informing the user about, in order of priority:
1. Replacement concept
2. "Consider" concept(s)
3. Nearest non-deprecated "parent" concept(s)
And allow to choose one or more of those, plus additional concepts from the given EDAM sub-ontology.

**Comment by matuskalas** [comment]
One additional note is wrt EDAM (https://github.com/edamontology/edamontology) (CC @joncison) :
The replacement concept of "Protein surface calculation (accessibility)" is now "Molecular surface calculation" with a definition of "Calculate the molecular surface area in proteins and other macromolecules", what is a logically wrong replacement. "Area" should be replaced and extended with a more generic plurality of notions.

**Comment by joncison** [comment]
please post to the edam tracker  J:)

**Comment by matuskalas** [comment]
Re @joncison: In EDAM it may be faster to just fix it, than to report or discuss it ;-)  The question stays how (*e.g.* where these definitions are leading wrt *e.g.* precision or abstraction)

**Comment by joncison** [comment]
This is a very important issue and needs more thought.  Latest idea from proposed automated QA/QC (https://docs.google.com/document/d/1ATj2zJOlbR3Edk6QyGvPX5HStZBknqfx1Fwqk4k0kqE/edit#heading=h.fffoc8urhpt8) is to silently fix deprecated concepts, or allow such fixes via "My Profile"

**Comment by joncison** [comment]
Need to: 
* fix legacy deprecated EDAM annotations systematically
* bake the behaviour (silent fix) into process for updating bio.tools for EDAM releases

**Comment by joncison** [comment]
The original issue is solved. 

In future, biotoolsLint will detect use of deprecated concepts, with action on EDAM and/or bio.tools side, see https://github.com/bio-tools/biotoolsLint/issues/6
