### ISSUE TITLE
Affiliation coupling

### ISSUE THREAD

**Issue by magnuspalmblad** [bio-tools/biotoolsregistry#99]
Maybe this has been defined somewhere and I just couldn't find it, but the top-level "Affiliation" for a bio.tools entry is coupled to whomever edits the entry, not the developer of the tool. While it makes sense that it should be clear who made or edited the entry, it looks as if the editor and their institution had something to do with the tool itself. Of course, in an ideal world all tool makers should register their software in bio.tools. But in reality, many tools will have to be registered by other volunteers.

There is no field for this top-level affiliation, although it can be edited in the JSON tab.

**Comment by joncison** [comment]
No, as things stand this is bad.  We are at least on top of it; it's one of the high-priority fixes.  If you have suggestions, please make them here:
https://biotools.sifterapp.com/issues/93

thanks!

**Comment by griffinp** [comment]
Are there any updates on this issue? We'd also love a fix on this... by the way I don't seem to be able to edit the affiliation in the JSON tab, I get a message saying I don't have permission to edit the JSON. 

Thank you! 
Pip Griffin, EMBL-ABR

**Comment by joncison** [comment]
Hey Pip,

A new content model is the top priority now that the conferences / holidays are done with.  Currently (in dev.bio.tools) a registered user who adds an entry "owns" that entry.  The next feature to add will be to allow that entry to be shared with others for editing, google-docs style (i.e. with named users, or everyone).  I think that would solve the problem?   @ekry can you advise when this will be ready ?

We also (right now) have an "Admin interface" that allows surgical changes directly to the database (any fields, any entries).     So we can efficiently make changes for you (if you send attach some file with the changes you want) or we an look at giving you access to this admin interface (depends the scope of what you have in mind).

We're also looking at allowing changes on certain fields by anyone: this needs a bit more thought as it cuts across the edit rights mechanism described in 1st paragraph.

**Comment by joncison** [comment]
Pip says ... 
"I (at EMBL-ABR, which is hosted at the University of Melbourne, hence my unimelb.edu.au email address) am adding tools that have nothing to do with me personally other than that they're partially or
fully developed by Australian researchers. So really I am doing this as a service: I don't have any role as a developer, provider or owner of the actual tools. However, 'unimelb.edu.au' appears as
default in the 'affiliation' field and I don't seem to have permission to edit the JSON file.


The best solution to our specific problem would currently be to allow me to edit the 'affiliation' field in the JSON file (and i would change this to the tool developer's institution). Does this
require Admin rights? If so, how should I request them?


It's not clear to me how this problem will manifest with the new data model: maybe it won't be an issue at all at that point? As long as the new model allows for the possibility that the person
submitting the tool actually has no credit at all themselves, it should b eokay...


It would on the other hand be nice (but not crucial) if there was a credit field in the new data model where we could acknowledge that the tool was submitted by EMBL-ABR (but developed, provided
etc. by others). I'm not sure if that fits with the model you describe."

**Comment by joncison** [comment]
I agree that the credit mechanism is extended to assign credit to the person creating the entry: https://github.com/bio-tools/biotoolsxsd/issues/52.  As you are adding the tools, once the new content sharing feature is in place, you'll be able to specify that the entries can be shared as you wish (as per above), ps.  it will also be possible to specify group(s) of named users have edit rights.

@ekry can confirm, but I think we can't allow editing of the affiliation: this field corresponds to accounts (from the old system) and we'll need it left unchanged for when we migrate to the new model (2016 Q4), at which point it will be replaced by the new credit mechanism (i.e. a named institute).

Would a temp. workaround be to provide us with a list of named tools / institutes?  We can then annotate all the entries via the Admin interface for you.

**Comment by griffinp** [comment]
Hi Jon,

sure, I can send you a list of tools with their corresponding institutes: will this cause any problems for my access to further editing these tools though? 

Shall I email them to you?

**Comment by griffinp** [comment]
Also, I am adding several tools per week - is this something you're prepared to support weekly until the new model is ready?

**Comment by joncison** [comment]
Update: 

The bio.tools content ownership model has been improved.

* the notion of "affiliation" is gone (actually preserved for now in it's own field - this will change soon, see below)
* a bio.tools user who creates an entry "owns" the edit rights, but can also share those rights with named or all other bio.tools users.  
* our candidate stable schema (1, 2) includes an improved credits model.  Comments are welcome (2, 3).  Support in bio.tools for it will occur in 3 stages, the 1st of which is scheduled in our roadmap (4) for Dec 16 and will include credits.
* we will migrate the preserved "affiliaton" annotations to the new credits model in Dec
* please keep on adding tools : tools from any provider (not just your own) are warmly welcome!  If you need new EDAM terms (or help with annotation) just ask (5).
* to credit the correct institute, just use the credit->institution field.   In the new credit model, you will also be able to credit yourself (I mean, as registrant) as "Documentor" of that tool.

(1) https://github.com/bio-tools/biotoolsSchema/tree/master/biotools-2.0-beta-02
(2) https://docs.google.com/document/d/1tqw7FELV4F_qzrTA9KpVYoORAeFPyY1ZOjaGTPN2H1E/edit
(3) https://github.com/bio-tools/biotoolsSchema/issues
(4) http://biotools.readthedocs.io/en/latest/changelog_roadmap.html
(5) https://github.com/edamontology/edamontology/issues

**Comment by joncison** [comment]
UPDATE:

In dev.bio.tools people can "Request edit rights" and "Request ownership" of tools  (will be pushed to production soon).  We're also contemplating adding a credit of "Documentor" on every entry which someone registers.

cc @hansioan FHI who also (Pip) can handle any surgical edits you need.

**Comment by joncison** [comment]
@griffinp @magnuspalmblad  - does the latest functionality address your needs / concerns?  can I close this issue now?

**Comment by joncison** [comment]
I'm assuming the changes we made addressed the issues; please reopen otherwise.
